### ISSUE TITLE
Issues with Search Path Order

### ISSUE THREAD

**Issue by kashperanto** [ThrowTheSwitch/Ceedling#100]
I am having issues with the search path order not applying consistently (or at least how I would expect it to operate).  I am trying to override a header file in my project (an IO map header with register definitions)  which was included (for no reason) in the header file of the module I am actually trying to mock using CMock.

In other words; I am trying to mock Dumb_Processor_Expert_Module.h, which itself includes IO_Map.h.  There is no reason for this inclusion (it is not necessary for compilation of the header, but Processor Expert puts it in there anyway).

In my first attempt at fixing this, I tried putting a mocked IO_Map.h file in the test/support directory to get rid of the actual mapping of register types to physical addresses (which also used non-standard @ operator).  Since the support directory is earlier in the search path order than my generated code directory (under :source:) I expected this to work fine, but it did not.  To get it to work I had to put a copy of Dumb_Processor_Expert_Module.h into the test/support directory (unmodified from the real file).  Without the identical copy it appears that CMock is attempting to use the original IO_Map.h file, but with the copy it uses the modified version of IO_Map.h in my test/support directory.

It looks to me like the search path order is only obeyed at the first level, and then subsequent includes will use the path of their parent file.  My configuration is correct as far as I can tell:
:paths:
  :test:
    - +:test/**
  :source:
    - ../Sources/**
    - ../Generated_Code/**
  :support:
    - test/support

My fix right now is to have a modified Dumb_Processor_Expert_Module.h file where I remove the problematic header, but I can easily see this bug causing problems if I end up testing modules which require the inclusion of other header files to compile.  If this is the desired/accepted behavior then I believe you should mention that in the documentation.

**Comment by mvandervoord** [comment]
I'm pretty sure that this is an issue with the compiler and not Ceedling. Ceedling just passes on the paths to the compiler in the order you've specified. Your compiler, however, goes through its normal search routine for headers when it reaches an #include. For most compilers that I am aware of, they ALWAYS start by searching the immediate directory for a header first, THEN your provided paths, THEN the system paths.

Perhaps the simplest solution for you, particularly since you said the header isn't even necessary, is to add a gate around the @include in the header file:

```
#ifndef TEST
#include "IO_Map.h"
#endif
```

In any case, I don't believe Ceedling can do much about this issue.

**Comment by kashperanto** [comment]
Thanks for the response; I was not aware of that.  I suppose I've never had a need to override existing files in this way before.  That seems counter-intuitive to me, but I'm sure someone else would think the exact opposite.  I would love to use conditional compilation instead of my current work-around, but unfortunately this is a generated file that would wipe out any such modifications.
