### ISSUE TITLE
No update/version option at command line

### ISSUE THREAD

**Issue by euripedesrocha** [ThrowTheSwitch/Ceedling#108]
Running ceedling(0.22) there's no update nor version option for the command. Running inside a project there's a version task. 
[Here we have](http://www.throwtheswitch.org/ceedling/) a description with both options. The documentation inside the created project doesn't have any mention to both commands. 

Add a update option is a good feature(I want to update unity/cmock at an old project) to have.

**Comment by mvandervoord** [comment]
:) This is already on the "coming soon" list. I'm glad to hear there is support for this idea!

**Comment by euripedesrocha** [comment]
Yes. I have few projects that could use an upgrade :) 

Just to inform that I had succesfully update just calling 

```
ceedling new name_of_the_project
```
And accepting the file modifications.

**Comment by mvandervoord** [comment]
:) I figured that would probably work... the only place it won't be perfect is where files are removed because it will leave them behind... but for the most part they will then be ignored.

Another option, for the future, is that you can create your project as `ceedling new projname --as_gem` and that will make it so you are ALWAYS working from your rubygem and upgrades are automatic. Depending on your situation, this can be a good or bad thing. ;)

**Comment by mvandervoord** [comment]
Ceedling now supports help, version, and update commands.
