### ISSUE TITLE
ceedling test:all fails because it can't find unity.cpp

### ISSUE THREAD

**Issue by iorix** [ThrowTheSwitch/Ceedling#110]
I am trying to setup a trial project to compile c++ files with extension .cpp.

I added the follwing to the project.yml file:
```
:extensions:
  :source: .cpp

:tools:
  :release_compiler:
  ...
```

This works fine. I can create the programs executable.

The problem starts when running this command: ceedling test:all

This is an excerpt of the error message:

```
Test 'test_myLib.cpp'
---------------------
Compiling test_myLib_runner.cpp...
Compiling test_myLib.cpp...
ERROR: Found no file 'unity.cpp' in search paths.
rake aborted!
```

Ceedling is looking for a unity.cpp. I found a file unity.c when searching the project directory structure.

Why is ceedling searching for unity.cpp instead of unity.c? Because of the :extensions:source: option in the project.yml file?
How can I correct this?

**Comment by Letme** [comment]
Might be a side discussion, but most C++ projects abuse some C code from somewhere so it would be nice if we could have sources as array of extensions instead of string like it is now. It will require a bit more change right?

**Comment by mvandervoord** [comment]
Ha! Now that's a funny one. I've not run across that one, though it's obvious in retrospect.

I agree that it would be best to accept an array of source options. That might be a pretty substantial change, though, since it affects make rules and source / header matching, etc. So it might be awhile before we can roll that out.

Until then, maybe you cheat and create a unity.cpp that just contains #include "unity.c" ?

**Comment by iorix** [comment]
Thanks for the work around.

The issue is solved by creating unity.cpp file next to the unit.c which include the latter.

The next issue is now with cmock.c. I solved that with the same workaround. Created a cmock.cpp file which includes cmock.c

Now a new error appears.

```
Test 'test_myLib.cpp'
---------------------
Compiling test_myLib_runner.cpp...
Compiling test_myLib.cpp...
Compiling unity.cpp...
Compiling cmock.cpp...
Linking test_myLib.app...
rake aborted!
NoMethodError: undefined method `include?' for nil:NilClass
/Volumes/users/oae/tmnt_projects/experiments/ceedling/MyFirstProject/vendor/ceedling/lib/ceedling/flaginator.rb:45:in `flag_down'
/Volumes/users/oae/tmnt_projects/experiments/ceedling/MyFirstProject/vendor/ceedling/lib/ceedling/generator.rb:113:in `generate_executable_file'
/Volumes/users/oae/tmnt_projects/experiments/ceedling/MyFirstProject/vendor/ceedling/lib/ceedling/rules_tests.rake:28:in `block in <top (required)>'
/Volumes/users/oae/tmnt_projects/experiments/ceedling/MyFirstProject/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
/Volumes/users/oae/tmnt_projects/experiments/ceedling/MyFirstProject/vendor/ceedling/lib/ceedling/test_invoker.rb:68:in `block in setup_and_invoke'
/Volumes/users/oae/tmnt_projects/experiments/ceedling/MyFirstProject/vendor/ceedling/lib/ceedling/test_invoker.rb:32:in `setup_and_invoke'
/Volumes/users/oae/tmnt_projects/experiments/ceedling/MyFirstProject/vendor/ceedling/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => build/test/results/test_myLib.pass => build/test/out/test_myLib.app
(See full trace by running task with –trace)
```

I have no Ruby knowledge and have no idea what is wrong here.


BTW: I needed to change two lines of code to be able to compile unit.c on a C++ compiler:

In file unity.c and function:
```
void UnityAssertEqualMemory( UNITY_INTERNAL_PTR expected,
                             UNITY_INTERNAL_PTR actual,
                             const _UU32 length,
                             const _UU32 num_elements,
                             const char* msg,
                             const UNITY_LINE_TYPE lineNumber)
```

The following 2 lines:
```
ptr_exp = (UNITY_INTERNAL_PTR)((_UP)ptr_exp + 1);
ptr_act = (UNITY_INTERNAL_PTR)((_UP)ptr_act + 1);

```
Should be replaced with this:
```
ptr_exp = (UNITY_PTR_ATTRIBUTE const unsigned char*)((_UP)ptr_exp + 1);
ptr_act = (UNITY_PTR_ATTRIBUTE const unsigned char*)((_UP)ptr_act + 1);
```

**Comment by iorix** [comment]
Update:
I found the root cause of the last error. It was an error in the project.yml file. The compilation of the unit test into an executable works fine now.

Thanks for your support.

**Comment by mvandervoord** [comment]
I'm glad you got the project file issue worked out. I'll keep this bug open as a reminder to myself that Ceedling needs to support .cpp and .c files simultaneously.

**Comment by brunobasto** [comment]
Any updates on this?

**Comment by brunobasto** [comment]
@iorix, can you share what was the fix you did to fix that error? Thanks

**Comment by iorix** [comment]
I only applied the workaround as described in my previous messages.

Search for the missing file with the same name but with extension '.c'. Create in the same dir a file with same name but with extension '.cpp'. include in this file the '.c' file.

This should do the trick.

**Comment by bheemann** [comment]
Hi,
is there an update planed for supporting .c and .cpp files?
I ran into the same problem like Letme:

`ERROR: Found no file 'unity.cpp' in search paths.rake aborted!`

my ceedling installation:

>Ceedling:: 0.28.3
CException:: 1.3.1.18
CMock:: 2.4.6.217
Unity:: 2.4.3.122

**Comment by cochld1** [comment]
I ran into this problem as well but our project is using ".cc" file extensions. 

I followed the work around instructions but then ran into an error where a <mock file>.cc file couldn't be found. Here is the example...

<<<
ceedling clobber test:pattern[a]

Clobbering all generated files...
(For large projects, this task may take a long time to complete)

Test 'test_a.cc'
----------------
Generating include list for b.h...
Creating mock for b...
Generating runner for test_a.cc...
Compiling test_a_runner.cc...
Compiling test_a.cc...
ERROR: Found no file 'mock_b.cc' in search paths.
>>>

It looks like .c mock files are being generated but .cc files are looked for during the compilation step.

I used the same work around for the mock files but it has to be redone every time I clobber.

**Comment by shubham-malasane** [comment]
@mvandervoord 
can we write test file for cpp files ?  if yes then is there any special functions are provided by unity test framework ? 
kindly waiting for your response..

**Comment by mvandervoord** [comment]
under normal circumstances, the answer would be yes. But it appears something is broken with this feature at the moment and I'm going to have to dig into it. I'd like to use this opportunity to support passing in a list of acceptable extensions so that they can be compiled properly instead of forcing the user to choose one.

**Comment by KishanShingala** [comment]
@mvandervoord

I am facing same issue try to setup project in c++ and getting Error: found no file 'unity.cpp' in search path. 

To resolve the issue I am trying suggested work around and tried to create a unity.cpp that just contains #include "unity.c" but not able to find unity.c location.

could you please help me out where should I look for unity.c file in my project structure?

**Comment by mvandervoord** [comment]
I'll have to check to see if this problem still exists in the pre-release gem. I believe this issue was taken care of a while ago, but I've not recently verified. 

It may be an issue, still. Unity is obviously a special case when working with cpp files. Ceedling should be using unity.c and cmock.c no matter which extension is being used elsewhere.

It would also good to support multiple extensions, so we can run against a mix of .cpp, .C, .c, .ino, .cc files, etc.

**Comment by mkarlesky** [comment]
Ceedling (pre-release version 0.32) now properly handles code files with extensions different than those of the core frameworks and generated files (but still only supports a single user-specified file extension). As for compilation with the stricter language standards of C++, it turns out that Ceedling could pretty much always do this if you were relying on the default gcc toolchain (and not using preprocessing features). 

The gcc compiler takes a command line flag `-x` that forces a particular interpreter. Without that flag, the compiler defaults to discerning the intended language interpreter from the file extension. For example, `.c` triggers C compilation while `.cc` and `.cpp` trigger C++ compilation (other file extensions map to other supported language interpreters and internal file formats as well). Ceedling's `:flags` and tool features allow a developer to simply add `-x c++` to compilation of all files which will force C++ interpretation of all code files in a test suite build regardless of file extension. The generated C code and other C frameworks that form a Ceedling test suite are already compliant with C++ strictness.

The frameworks Ceedling pulls in (e.g. Unity and CMock) all have `.c` extensions. Code files that are generated during a test suite build (e.g. test runners and mocks) also default to `.c` extensions. Until version 0.32 this actually spelled some trouble for `:extensions` settings. You could specify something other than `.c` for code files, but in most cases this would cause problems such as this issue thread first noted. Ceedling 0.32 now properly distinguishes framework and generated code files from project code files as well as properly executes its preprocessing features regardless of file extension.

Version 0.32's abilities to compile C with C++ strictness remain simply a function of flag handling and require a user to insert the appropriate flag (again, `-x c++` when using the default gcc toolchain). Ultimately, this is probably best handled with some kind of documentation “cookbook” that explains the combination of features and settings to accomplish this rather than baking in further functionality.

**Comment by vitara-campbell** [comment]
Has anyone tried unity with .elf build output?
