### ISSUE TITLE
Error on Creating a Module 

### ISSUE THREAD

**Issue by chaosAD** [ThrowTheSwitch/Ceedling#183]
I ran Ceedling under `ruby 2.4.1p111 (2017-03-22 revision 58053) [i386-mingw32]` (Windows). The Ceedling version is 0.27.0. When I issued `rake module:create[MyExample]`, it generated the following error:
```
rake aborted!
ERROR: File myexample already exists. Exiting.
C:/MyProject/vendor/ceedling/vendor/unity/auto/generate_module.rb:197:in `generate'
C:/MyProject/vendor/ceedling/plugins/module_generator/lib/module_generator.rb:17:in `create'
vendor/ceedling/plugins/module_generator/module_generator.rake:12:in `block (3 levels) in <top (required)>'
vendor/ceedling/plugins/module_generator/module_generator.rake:12:in `each'
vendor/ceedling/plugins/module_generator/module_generator.rake:12:in `block (2 levels) in <top (required)>'
Tasks: TOP => module:create
(See full trace by running task with --trace)
File src/myexample.c created
File src/myexample.h created
File test/test_myexample.c created
Generate Complete
```
However the necessary files were generated. After testing the code a bit, I discovered it attempted to create the 3 files twice, therefore the errors.

Also the files were created ignoring the capitalization.

**Comment by mvandervoord** [comment]
Hi. This was already fixed in 0.28.0. Today we released 0.28.1, which I just verified also has this issue fixed.

**Comment by dpostorivo** [comment]
@mvandervoord  Due to the last line:

> Also the files were created ignoring the capitalization.

I suggest we at least keep this open. I honestly never noticed that was the case and we should either make it so it is case sensitive or document it.

**Comment by mvandervoord** [comment]
Ah. Missed that line. Interesting!

**Comment by mvandervoord** [comment]
Ah I see now. It's because we recently improved the featureset of Unity's module generator script (which Ceedling is using for this). The script now accepts extra configuration like so:

```
:module_generator:
  :naming: :bumpy
```
Options are bumpy, snake, caps, and camel. It helps to keep the file naming convention enforced, particularly when they start using patterns, like so:

```
ceedling module:generate[Analog,MCH]
```

I think, though, that we should probably tweak Unity's handling of this to not do any conversions when no naming convention has been specified. This should fix the issue as far as Ceedling is concerned (and will allow Ceedling to still support the new feature).

Thoughts?

**Comment by mvandervoord** [comment]
I went ahead with this plan. If you don't specify anything, it won't change your names. If you specify a naming convention, it will enforce it. 

This should roll out with the next release (or grab the source if you wish)
