### ISSUE TITLE
Can't change paths on module generator 

### ISSUE THREAD

**Issue by pkazakoff** [ThrowTheSwitch/Ceedling#208]
Based on what I read in documentation in CeedlingPacket.md, I should be able to make the module generator put its generated .h files in the inc/ directory by adding this to project.yml:

```yaml
# Module generation
:module_generator:
    :inc_root:      inc/
```
However, ceedling seems to ignore these settings:

```
C:\Users\pkazakoff\STM32_Workspaces\Xmas_Gift\Xmas_Gift>ceedling module:create[testmod]
File src/testmod.c created
File src/testmod.h created
File test/test_testmod.c created
Generate Complete
```

I am running the latest ceedling gem (0.28.2). My full project.yml is here: https://pastebin.com/FF34P4rd.

**Comment by laurensmiers** [comment]
Hi,

Did you create your project with "ceedling new <project>"?
Because I have the same issue. It seems the latest changes of the module_generator are not incorparated yet in the gem-install of ceedling.
If you didn't choose --as_gem when creating your project, you can just update to the latest ceedling in your project:
- go to your project_root/vendor, delete the ceedling folder and checkout the latest ceedling in there:
$> git clone --recursive https://github.com/throwtheswitch/ceedling.git

If you run the module_generator now, you should be able to change the inc/ path.

**Comment by mvandervoord** [comment]
Does anyone know if this is still an issue?

**Comment by davidvanwyk** [comment]
@mvandervoord This is still an issue. With the ceedling one gets with ceedling new, you can set the src_root, but inc_root is ignored - whereas with the latest build using the git clone methodology just causes an error if the file already exists in src_root; as per #215.

**Comment by GrzegorzFedoryka** [comment]
Hi, i had that problem and cloning solved it but now i have second problem - test source file can't see header file now. Does anyone know how to fix this?

**Comment by GrzegorzFedoryka** [comment]
Ok, i've found that. In project.yml file add line -inc/** in this place
:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
    - inc/**
  :support:
    - test/support

**Comment by dfridley** [comment]
Works as intended if I delete the "vendor/ceedling/plugins/module_generator/config" folder
