### ISSUE TITLE
UNITY_INCLUDE_64 getting double defined

### ISSUE THREAD

**Issue by mvandervoord** [ThrowTheSwitch/Ceedling#255]
I've heard complaints that UNITY_INCLUDE_64 being placed in :unity: :defines: will result in it being double-defined (both through the command line AND injected into the header?)

**Comment by dpostorivo** [comment]
I've worked on two different solutions for this. Both alone will fix the issue alone so we should decide which one should  be done or if both being done make sense.

1. Remove the UNITY_INCLUDE_64 from the runner define config since it's already in the command line. This is the most direct solution, but feels more like a hack then a solution.

2. Modify generate_test_runner to add ifndef guards against double defines. If this is done, it won't be defined twice since it's already defined.

**Comment by art-of-dom** [comment]
This is fixed in 0.29.0.
