### ISSUE TITLE
Default plugin paths broken

### ISSUE THREAD

**Issue by tbates-redarc** [ThrowTheSwitch/Ceedling#262]
Pull request #167 breaks my build system as the default plugins are no longer loaded. The comment on the change in defaults.rb suggests that the default path is being injected somewhere else but it isn't working for me and I can't work out where it should be being injected. Ceedling.load_path is defined in lib/ceedling.rb but never called as far as I can tell.

I am still calling Ceedling through `rake` (and I'd like this to continue to be supported as we also use Rake for other things in our build system that don't depend on Ceedling, but I get the feeling that this is being phased out as a supported use case), but I can't see anywhere in `bin/ceedling` that would be injecting the default load_path either.

Can you please tell me where the default plugin path is supposed to be configured and why my change to defaults.rb from #125 was rolled back by #167?

**Comment by tbates-redarc** [comment]
@dpostorivo can you perhaps weigh in?

**Comment by art-of-dom** [comment]
This was a problem that was not only happening for me but happening for others. I'm not sure why your build system is acting different way. If you can post your Ruby version and and the version of season you are currently using I can try to dig into it.

I also use ceedling through rake and it is working in my environment. My guess would be that something is up with the project.yml and if you can supply it I might be able to help.

This change was almost a year ago and I'm slightly hazy on the details. All I can remember is that the plugins were included twice and there is no detection for this. My Ruby is a little bit better now so maybe a second look would be fruitful.

**Comment by art-of-dom** [comment]
After reviewing the process in my head, the default config path should only be included if no config is specified.  It doesn't make sense to always include it especially when it is already specified or another location is specified since having the same path twice or conflicting plugins may result in problems as seen in #166.

**Comment by tbates-redarc** [comment]
I'm currently on Ceedling 0.27.0 (from before your change) and found this issue when upgrading to 0.28.2 (also exists on current master). Ruby 2.4.2p198. I don't think it's a Ruby version issue though. `CEEDLING_PLUGINS` variable that I created in #125 is not being used now, perhaps if you look at your current version and work out where the plugin paths are being set up? Thanks.

**Comment by art-of-dom** [comment]
Having that be the default caused issues with the generated project.yml which includes the plugin in path. Ceedling has no capabilities of   detecting duplicate plugin in paths which caused the issue in #166.

The solution that i think would work best is to only use that variable if and only if there are no other paths specified since people may have their own plugins they've modified and not always want to use the defaults.

Ceedling should also be able to detect duplicate paths, but that is something that can be addressed at a later time.

**Comment by tbates-redarc** [comment]
Got a proposed fix (#263) which avoids loading the same plugin from multiple paths and puts the default path at the end of the search list, so any user-provided paths should take precedence over it. Can you please test it on your project?
