### ISSUE TITLE
undefined reference to suiteSetUp, suiteTearDown brand new project

### ISSUE THREAD

**Issue by brennanjleahey** [ThrowTheSwitch/Ceedling#337]
STR: 
1. Create new project
2. Navigate to project folder in cmd line
3. create new module (module:create[lights])
4. test (either ceedling or ceedling test:all)

Pretty broken bug, cannot move past creating a module on a brand new project. What gives?

**Comment by mvandervoord** [comment]
What problem is this procedure giving you? What platform and toolchain are you using?

**Comment by brennanjleahey** [comment]
This problem persists with even trying to test the temp_sensor example. 
Here's the rundown when I try testing the temp_sensor: 

`C:\Users\bleahey\ceed_main\temp_sensor>ceedling

C:\Users\bleahey\ceed_main\temp_sensor>ruby vendor\ceedling\bin\ceedling


Test 'TestAdcConductor.c'
-------------------------
Linking TestAdcConductor.out...
build/test/out/c/TestAdcConductor_runner.o: In function `suite_setup':
/cygdrive/c/Users/bleahey/ceed_main/temp_sensor/build/test/runners/TestAdcConduc
tor_runner.c:79: undefined reference to `suiteSetUp'
/cygdrive/c/Users/bleahey/ceed_main/temp_sensor/build/test/runners/TestAdcConduc
tor_runner.c:79:(.text+0x7c): relocation truncated to fit: R_X86_64_PC32 against
 undefined symbol `suiteSetUp'
build/test/out/c/TestAdcConductor_runner.o: In function `suite_teardown':
/cygdrive/c/Users/bleahey/ceed_main/temp_sensor/build/test/runners/TestAdcConduc
tor_runner.c:87: undefined reference to `suiteTearDown'
/cygdrive/c/Users/bleahey/ceed_main/temp_sensor/build/test/runners/TestAdcConduc
tor_runner.c:87:(.text+0x96): relocation truncated to fit: R_X86_64_PC32 against
 undefined symbol `suiteTearDown'
collect2: error: ld returned 1 exit status
ERROR: Shell command failed.
> Shell executed command:
'gcc.exe "build/test/out/c/TestAdcConductor_runner.o" "build/test/out/c/TestAdcC
onductor.o" "build/test/out/c/MockAdcModel.o" "build/test/out/c/MockAdcHardware.
o" "build/test/out/c/unity.o" "build/test/out/c/UnityHelper.o" "build/test/out/c
/AdcConductor.o" "build/test/out/c/cmock.o" -o "build/test/out/TestAdcConductor.
out" -lm'
> And exited with status: [1].


NOTICE: If the linker reports missing symbols, the following may be to blame:
  1. Test lacks #include statements corresponding to needed source files.
  2. Project search paths do not contain source files corresponding to #include
statements in the test.
  3. Test does not #include needed mocks.

rake aborted!

C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/generator.rb
:144:in `rescue in generate_executable_file'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/generator.rb
:130:in `generate_executable_file'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/rules_tests.
rake:41:in `block in <top (required)>'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/task_invoker
.rb:86:in `invoke_test_results'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker
.rb:123:in `block in setup_and_invoke'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker
.rb:63:in `setup_and_invoke'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/tasks_tests.
rake:11:in `block (2 levels) in <top (required)>'
vendor/ceedling/bin/ceedling:311:in `block in <main>'
vendor/ceedling/bin/ceedling:298:in `<main>'

Caused by:
ShellExecutionException: ShellExecutionException
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/tool_executo
r.rb:82:in `exec'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/generator.rb
:129:in `generate_executable_file'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/rules_tests.
rake:41:in `block in <top (required)>'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/task_invoker
.rb:86:in `invoke_test_results'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker
.rb:123:in `block in setup_and_invoke'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker
.rb:63:in `setup_and_invoke'
C:/Users/bleahey/ceed_main/temp_sensor/vendor/ceedling/lib/ceedling/tasks_tests.
rake:11:in `block (2 levels) in <top (required)>'
vendor/ceedling/bin/ceedling:311:in `block in <main>'
vendor/ceedling/bin/ceedling:298:in `<main>'
Tasks: TOP => build/test/results/TestAdcConductor.pass => build/test/out/TestAdc
Conductor.out
(See full trace by running task with --trace)
ERROR: Ceedling Failed

C:\Users\bleahey\ceed_main\temp_sensor>`

Downloaded GCC via cygwin, made sure to path to bin folder. Very new to this, is there a better alternative to cygwin for GCC / C testing?

**Comment by mvandervoord** [comment]
I tend to use mingw myself on windows, but cygwin should be fine. I don't *think* that's going to be the issue.

Instead of executing it the way you are now, can you try this:

```ceedling verbosity[4] test:all```

It will return a lot of information, very likely. You don't need to share all of it. I'm looking to see which files are being linked together in the link statement.

**Comment by brennanjleahey** [comment]
Resolved: Added UNITY_NO_WEAK into common defines in yml file

`  :common: &common_defines [UNITY_NO_WEAK]`

**Comment by mvandervoord** [comment]
Out of curiosity, what version of gcc is your install of cygwin using? It seems curious that it doesn't support weak functions.

**Comment by brennanjleahey** [comment]
latest and greatest cygwin fresh install but only selected packages with gcc in the description

**Comment by orange2348** [comment]
I meet the problem too, and when i add UNITY_NO_WEAK to the project.yml， the issue is fixed.
The gccc version i used is gcc version 7.4.0 (GCC). See below.

> Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/7.4.0/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-7.4.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-comp
atible
Thread model: posix
gcc version 7.4.0 (GCC)

**Comment by joel-felcana** [comment]
Had a similar issue with gcc version 7.4. The issue doesn't occur in gcc 8.2, so I guess it has something to do with that particular gcc version? I'm on windows, using MSYS2.
