### ISSUE TITLE
How to build project?

### ISSUE THREAD

**Issue by IvanRibakov** [ThrowTheSwitch/Ceedling#351]
I'm new to Ceedling. I've been going through https://github.com/ThrowTheSwitch/Ceedling/blob/master/docs/CeedlingPacket.md to help me get started and was expecting that after I created an empty project and placed some dummy source files inside it I will be able to just compile them (in hope to tie Ceedling with my IDE (CLion)). The closest command that I found in the docs was `ceedling release` (as described in "Now What? How Do I Make It GO?" section). However, when I ran `ceedling help` from inside the project directory, I got the following output:

```
$ ceedling help
ceedling clean                        # Delete all build artifacts and temporary products
ceedling clobber                      # Delete all generated files (and build artifacts)
ceedling environment                  # List all configured environment variables
ceedling files:header                 # List all collected header files
ceedling files:source                 # List all collected source files
ceedling files:test                   # List all collected test files
ceedling logging                      # Enable logging
ceedling module:create[module_path]   # Generate module (source, header and test files)
ceedling module:destroy[module_path]  # Destroy module (source, header and test files)
ceedling paths:source                 # List all collected source paths
ceedling paths:support                # List all collected support paths
ceedling paths:test                   # List all collected test paths
ceedling summary                      # Execute plugin result summaries (no build triggering)
ceedling test:*                       # Run single test ([*] real test or source file name, no path)
ceedling test:all                     # Run all unit tests (also just 'test' works)
ceedling test:delta                   # Run tests for changed files
ceedling test:path[dir]               # Run tests whose test path contains [dir] or [dir] substring
ceedling test:pattern[regex]          # Run tests by matching regular expression pattern
ceedling verbosity[level]             # Set verbose output (silent:[0] - obnoxious:[4])
ceedling version                      # Display build environment version info
```

No `release` command seems to be available. I guess I'm missing something from the docs... I would appreciate if someone could point me in the right direction of how can I compile a Ceedling project.

For the record, the steps I took:
1. `ceedling new <my_project>`
2. `cd <my_project>`
3. Created basic .c/h in `src/`
4. Tried to run `ceedling release`
```
$ ceedling version
  Ceedling:: 0.28.3
CException:: 1.3.1.18
     CMock:: 2.4.6.217
     Unity:: 2.4.3.122
```

**Comment by IvanRibakov** [comment]
Bump. 

I get it's a beginner's question but a quick pointing in the right direction will be sufficient and much appreciated.

**Comment by mvandervoord** [comment]
Hi Ivan

By "build a project", I am going to assume that you mean "build the release" and not "build and execute the tests". If that assumption is incorrect, please correct me.

You *did* find the correct command for building a release from ceedling:

```
ceedling release
```

The reason it's not showing up on your list is going to be something to do with your configuration. By default, a release build isn't usually enabled. While we can assume that a native gcc build is sufficient for most unit testing, a native gcc is very rarely correct for most users. Many of our users are writing embedded software, which is likely going to need cross-compilation for a different platform.

In any case, there are a few steps to getting release builds working. You can find more information on each of these items in the ceedlingpacket. 

1 -- In the first section of your project.yml file, you need to enable release builds:

```
:project:
  :release_build: TRUE
```

2 -- You'll have to describe the release build a bit so ceedling knows what you're looking for:

```
:release_build:
  :output: SuperSecretExecutable.hex
  :use_assembly: TRUE
  :artifacts:
    - SuperSecretExecutable.map
```

3 -- You'll have to double-check paths and/or files for release. Most likely you handled these already when you set up your tests, with the `source` and `includes` sections you may have already adjusted. If there are things that only your release is going to need, you can optionally include them here:

```
:paths:
  :release_toolchain_include:
    - blah/blah
```

4 -- The biggest step is getting all the tools set up. We do this with the tools section. You'll at least need a compiler and linker defined. Depending on your other settings, you may also need a preprocessor or assembler. There are way too many details to describe here, but you're looking for these sections:

```
:tools:
  :release_compiler:
  :release_assembler:
  :release_linker:
  :release_dependencies_generator:
```

5 -- Very likely, you're going to need to revisit the defines that you are injecting into your build process. Those can be added to these sections:

```
:defines:
  :release:
  :release_preprocess:
```

6 -- You may end up needing to add specific libraries. There is also a section for this:

```
:libraries:
  :placement: :end
  :source:
	- m
  :system:
  :flag: “${1}” # or “-L ${1}” for example
```

At that point, you should be able to run releases.

**Comment by IvanRibakov** [comment]
Thank you for the expanded answer Mark!

I'm afraid your initial assumption was wrong. All I'm trying to do is find the command to compile the sources with Ceedling so that I can configure my IDE accordingly.

Based on your answer I understood that `release` command is there to help with cross-compilation (is that right btw?). So what if I just need to build for one platform using native gcc (I'm evaluating Ceedling for non-embedded project use)? Is `release` command (and the configuration steps that you described above) my only option or is there some simpler alternative to `cmake ..` +  `make all`?

**Comment by mvandervoord** [comment]
Hm. I'm still not sure that we're talking about the same things.

You're still talking about a single compilation unit, which makes me think that either you are still discussing an actual build (no tests) or that you don't realize that ceedling builds multiple executables when building tests.

So I'll do a quick answer for both and you can ask further questions if needed. Cool?

To build and run all of the tests that you have written, the command is as follows:

```
ceedling test:all
```

This will make a test executable for EACH test.c file that you have in your test directories. Most often, you will write a test.c file for each source file you wish to test. For example, if you had the files `spi.c` and `i2c.c`, then you would likely write two test files `test_spi.c` and `test_i2c.c`. Those would get compiled into two separate test executables and run one at a time. The results would all be collected and summarized for you by ceedling.

If, on the other hand, you were looking to compile `i2c.c` and `spi.c` and probably other files like `main.c` and compile them all together so that you have an executable, then you want to use the procedure that I described above. The `release` feature is for the purpose of building actual executables that do NOT contain tests. It doesn't matter if the platform is native, a simulator, an embedded processor, etc... the overall technique is still the same.

You are definitely able to build the releases with `make` or any other tool as well. Ceedling shines in managing test suites. It has the ability to also build releases to make it convenient for people, but that doesn't mean you need to use that feature. Many teams choose to test with Ceedling but build their release code with other tools.

**Comment by IvanRibakov** [comment]
> The release feature is for the purpose of building actual executables that do NOT contain tests

Got it.

> It has the ability to also build releases to make it convenient for people, but that doesn't mean you need to use that feature. Many teams choose to test with Ceedling but build their release code with other tools.

At this point I think my original question has been answered and the answer is - Ceedling can be used side by side with other build tools, so use Ceedling for what it's best at, i.e. running tests.

Thanks for taking your time to break down things for me, Mark!
