### ISSUE TITLE
"undefined reference function" although include header files

### ISSUE THREAD

**Issue by congtmbg** [ThrowTheSwitch/Ceedling#361]
Dear every body,
I'm doing unit test project, and i have a issue below:
"src" folder:
 - src/sub_folder/file1.h
 - src/sub_folder/file1.c
 - src/sub_folder/file2.h
 - src/sub_folder/file2.c
4 files: file1.h, file2.h, file1.c ,file2.c are in same sub folder.
"test" folder:
- test/sub_folder/test_file1.c: unit test all function well, have not issue.
- test/sub_folder/test_file2.c: test_file2.c have just include "file1.h", because some function in test_file2.c use function in file1.h. But when ceedling build, i have issue 'undefined reference function", this function from file1.h.
test_file1.c and test_file2.c are in same sub folder.
Can you tell me about solution to fix that, please?
Thanks.

**Comment by mvandervoord** [comment]
The situation as you describe it seems like everything is set up the way it should. test_file1 should build with file1. test_file2 should build with both file1 and file2, because you're including both. 

If you didn't want the actual full source code for file1 in your test_file2, you could instead include "mock_file1", but that's not the problem you're running into at the moment.

Since you haven't included any of the real code or configuration here, I'm just taking guesses at what mistake you could have made. Here are some common ones:

If you're on Windows, you're going to need to still make sure that the capitalization matches. If the files are "file1.h" and "File1.c", that's going to be a problem... or if the file is called "File1.h" and you call it "file1.h" in the test, that would also be a problem. Windows command line is case insensitive, but most tools running on it are not.

It's possible the function itself is misnamed in test2. If your release code is building, that is unlikely.

I assume that both your test and src subfolders are added in ceedling's path listings? When you do includes, you are #including just the name of the file, not the folder, correct?

If neither of these are the problem, it would be useful to get more information. For example, is the undefined reference being reported by the linker or the compiler?

**Comment by congtmbg** [comment]
Dear you,
I assume that both your test and src subfolders are added in ceedling's path listings? When you do includes, you are #including just the name of the file, not the folder, correct?
-> Yes. 
My  test and src subfolders are added in ceedling's path listings.
src/sub_folder**
src/**
test/**
test/sub_folder/**

I'm include only mame of headers files in source code, not path of header files, like this:
#include "file1.h"
#include "file2.h"

For example, is the undefined reference being reported by the linker or the compiler?
-> I will check console log (linux) again.
I'll feedback for you soon.
Thank you.

**Comment by congtmbg** [comment]
Dear you, 
Below is  information about ceedling version, os which I using.
1.
cong@cong-Inspiron-3470:~/unit_test/neo-firmware/unit_test$ ceedling version
  Ceedling:: 0.28.3
CException:: 1.3.1.18
     CMock:: 2.4.6.217
     Unity:: 2.4.3.122
2.
OS: ubuntu 16.04 LTS 64 bit.

**Comment by congtmbg** [comment]
> If neither of these are the problem, it would be useful to get more information. For example, is the undefined reference being reported by the linker or the compiler?
-> the undefined reference was reported by the linker.
Currentty, I instead include "mock_file1".
You can tell me about solutions later.
I will close issue now.
Excuse me! Do you know any free static code analysis tool which check C source code?
Example checking: about memory leak...
Thank you so much!

**Comment by congtmbg** [comment]
Excuse me!
Beside github, can I contact you quickly via another thing?
It is my another email: congtm.tts@gmail.com

**Comment by Letme** [comment]
Cppcheck is free static analysis tool

**Comment by Letme** [comment]
I think it can. But since you have a simple example you can run it through and see what it reports. Just be aware that it is same as a compiler where --all does not actually enable all checkers. Check the docs.

**Comment by congtmbg** [comment]
> I think it can. But since you have a simple example you can run it through and see what it reports. Just be aware that it is same as a compiler where --all does not actually enable all checkers. Check the docs.

Thank you.
If I have any problem when i use cppcheck tool, i need your helps.

**Comment by ksuryagiridhar** [comment]
> > If neither of these are the problem, it would be useful to get more information. For example, is the undefined reference being reported by the linker or the compiler?
> > -> the undefined reference was reported by the linker.
> > Currentty, I instead include "mock_file1".
> > You can tell me about solutions later.
> > I will close issue now.
> > Excuse me! Do you know any free static code analysis tool which check C source code?
> > Example checking: about memory leak...
> > Thank you so much!

Hello,

I also have similar situation but mocking the code file is causing some other issues. Do you have any other solutions than using the mock file? 

Thank you,
Suryagiridhar
