### ISSUE TITLE
Ceedling test:all runs fine on ubuntu, fails on macos

### ISSUE THREAD

**Issue by krish2487** [ThrowTheSwitch/Ceedling#380]
Hello,
I was wondering if I did something wrong or if I need to do something specific for macos and ceedling.
I am working on a project where I am testing a library. I work with the same code on my laptop (macbook air) and desktop (ubuntu 18.04). The firmware is in its own gitlab repo with a gitlab-ci.yml file for CI - CD operations (this is important since the CI pipelines always complete successfully)

Whenever I develop some test / code, I run ceedling, verify that it runs and then push it to gitlab. If I have to change my workspace machine then I do a git pull first and then the same process all over again.

All this brief to arrive at the issue at hand. I made some changes, wrote some tests on the ubuntu machine and verified that ceedling ran the tests. It did - successfully. I pushed the same to gitlab, the CI pipeline there also completed successfully. Then I moved to my laptop much later and did a git pull. then tried adding some other feature. It failed. I tried "git reset - hard" to work off the same codebase as that of the ubuntu machine and the gitlab repo.. Even that failed. 
The error I get is 
```
"Running test_hd44870.out...
sh: line 1: 68565 Segmentation fault: 11  build/test/out/test_hd44870.out 2>&1

ERROR: Test executable "test_hd44870.out" failed.
> Produced no output to $stdout.
> And exited with status: [0] (count of failed tests).
> This is often a symptom of a bad memory access in source or test code.

rake aborted!
```
on the mac. I am at my wits end as to why this is happening..
I suspect it might be because of the gcc differences between the Macos and the ubuntu machine.

Any help or insight into this is highly appreciated!! 
Thanks in advance!! :-)

**Comment by mvandervoord** [comment]
Yes, given the error you're receiving, it's most likely a difference in the versions of gcc... but more to the point: it's most likely an error in your release or test code. One of the other is likely segfaulting due to one of the following issues:

* uninitialized pointer
* stack overflow (particularly for recursive functions)
* memory access error (often the result of pointer problems or non-terminated strings).

There are other possibilities, but in order to narrow it down, I would comment out half the tests in the test file that is crashing. If it works, uncomment more... if it doesn't comment more... narrow it down until you find a test (or tests) that break things. It usually starts to get more obvious what the problem is at that point.

I'm certainly not ruling out the potential of a ceedling or similar bug... I'm just saying that it's your executable that is crashing, which makes it more likely that it's something to do with the application itself.

Best of luck!

Mark

**Comment by krish2487** [comment]
Thanks for the prompt response @mvandervoord !! :-)
I think you are onto something. 
One of the test is a check for catching uninitialized pointers.

I used this wonderful article from matt chernosky
http://www.electronvector.com/blog/unit-testing-with-asserts
to use cexception and custom asserts.

The idea is this. A configuration structure that has several configuration values and function pointer members. In a couple of the tests, I am passing function pointers that are declared but not pointing to anything. I wanted to catch the uninitialized function pointers using the custom asserts. 

I am guessing this is where the problem is arising. I did try you suggestion of commenting out these tests and sure enough the tests run even on mac.

I did use the stock definitions provided in the article I mentioned above except for the custom assert definition. I used the following code

```
#ifdef TEST
#include "CException.h"
#define assert(condition)  if(!(condition)) Throw(0)       
#else
#define assert(condition) ((condition) ? (void)0 : printf("[Assert error] - %s : %d\n",__FILE__,__LINE__ );
#endif
```

Is there anyway I can get these tests to run on a mac?

On a side note, how did the same test compile on an ubuntu machine. Should the uninitialized pointer cause the same issue on a ubuntu platform as well?

Again, thanks for the prompt response. :-D

**Comment by mvandervoord** [comment]
I would suspect that there is a situation where you're not actually catching the thrown exception, in that case. Note the bottom of the article where it's talking about using Try ... Catch. It is important that anything that might throw that error be wrapped in a Try... Catch in order to process the failure if it occurs.

This is a pretty unconventional approach to testing something like this, but it seems like it should work.

I suspect the difference between ubuntu and macos in this case are just a matter of what memory is laying around, so that when the error occurs, it is able to exit gracefully (or not).

Have no fear about using macos in general. It's my primary development machine... so Ceedling is more likely to work well with macos than anything else. ;)

**Comment by krish2487** [comment]
My apologies, I forgot to add the remaining bit in the last post.
This is the complementary macro set for the try catch block.

```
#include "CException.h"

#define TEST_ASSERT_FAIL_ASSERT(_code_under_test)         \
{                                                         \
  CEXCEPTION_T e;                                         \
  Try {                                                   \
    _code_under_test;                                     \
    TEST_FAIL_MESSAGE("Code under test did not assert");  \
  } Catch(e) {}                                           \
}

#define TEST_ASSERT_PASS_ASSERT(_code_under_test)               \
{                                                               \
  CEXCEPTION_T e;                                               \
  Try {                                                         \
    _code_under_test;                                           \
  } Catch(e) {                                                  \
    TEST_FAIL_MESSAGE("Code under test failed an assertion");   \
  }                                                             \
}
```


and the actual test code bit. Please excuse for the incomplete set.


```
	data_ptr lcd_send_data;
	command_ptr lcd_send_command;
	delay_ptr delay_microseconds;

	lcd.function_set = FUNCTION_SET_BASE;
	lcd.entry_mode = ENTRY_MODE_BASE;
	lcd.display_shift = DISPLAY_SHIFT_BASE;
	lcd.display_control = DISPLAY_CONTROL_BASE;
	lcd.delay_useconds = delay_microseconds;
	lcd.delay_mseconds = delay_microseconds;
	lcd.lcd_send_databyte = lcd_send_data;
	lcd.lcd_send_commandbyte = lcd_send_command;


	TEST_ASSERT_PASS_ASSERT(lcd_init(&lcd));
```

but you get the idea.. The function pointers are declared but not pointing to anything... 
The structure is set up and the custom test asserts call the function under test.

If the macro does expand correctly, then the function (along with the throw  section) should be wrapped exactly in the try catch block.

MAybe my sleep deprived head is not seeing it but manually expanding it, i would expect it to basically compile and fail the test or pass it. not cause a segfault.

Thanks for the tip about Macos. :-) That is a huge relief..

It seems like a decent compromise between unit testing and using asserts for build code. :-)

**Comment by krish2487** [comment]
Now this is getting really really weird.
running ceedling or ceedling test:all causes a segfault while running
but, running ceedling gcov:all utils:gcov executes it completely!!!

```
Test 'test_hd44870.c'
---------------------
Creating mock for function_prototypes...
Generating runner for test_hd44870.c...
Compiling test_hd44870_runner.c...
Compiling test_hd44870.c...
Compiling mock_function_prototypes.c...
Compiling unity.c...
Compiling hd44780.c with coverage...
Compiling CException.c...
Compiling cmock.c...
Linking test_hd44870.out...
Running test_hd44870.out...
Creating a detailed html report of gcov results in build/artifacts/gcov/GcovCoverageResults.html...
Done.

--------------------------
GCOV: OVERALL TEST SUMMARY
--------------------------
TESTED:  4
PASSED:  4
FAILED:  0
IGNORED: 0


---------------------------
GCOV: CODE COVERAGE SUMMARY
---------------------------
hd44780.c Lines executed:100.00% of 19
hd44780.c Branches executed:100.00% of 10
hd44780.c Taken at least once:80.00% of 10
hd44780.c No calls

```

It looks like the tests are passing when running with gcov.
@mvandervoord  any insight into why this is happening??
I am pretty confused now, should I understand that my tests are broken or I am handling the process wrong??

Thanks for the help in advance!! :-)

**Comment by mvandervoord** [comment]
Of course I can't know for sure without being able to reproduce the issue, but my instinct stills says it's memory related. When you're working with a situation where there is memory that isn't being referenced properly (because the stack is corrupted or a pointer is wrong or whatever), it can look different with the smallest changes in code, because things are moved in memory and now the corrupted spot is somewhere else. It doesn't surprise me to hear it's different with gcov running... this is going to insert a lot of extra checks into your codebase which is definitely going to change the working memory.

The most common problem when working with CException is relying on memory that has changed between the Try and the Throw, because it can't be relied upon (depending upon the specific compile, the memory may show up changed, or it may not, when the stack unwinds). I don't SEE that happening in your example here, but it might be. You'd want to look for things like lines which use variables after your TEST_ASERT_PASS_ASSERT or memory being used which may no longer be valid. Do you have anything in teardown or anything after TEST_ASSERT_PASS_ASSERT in any of your tests? Are you also running CMock, requiring it to do post-test validation?

**Comment by krish2487** [comment]
I would rather trust your gut instinct rather than my code. :-) 
I am still learning the ropes.. I am also certain it is my understanding and consequently my code that is flawed.
If I can trouble you for a bit, would you mind looking at the code and shed some light on where I am going wrong.

https://gitlab.com/krish2487/hd44780_v2

This is a link to the repo.  You sholuld be able to simply clone it and run ceedling to reproduce my errors..  There are two files under test/support which define the custom assert macros and function prototypes (which I am mocking in the test file).
There are just 4 tests I am presently running. 
1. checking if a NULL pointer is passed to the FUT
2. Checking if any of the structure members are not set.
3. Checking if the structure members are set but the function pointer members are not pointing to a function.
4. Checking if all the members are correctly set and if the function calls all the member functions in order.

There is nothing in the setup and teardown are empty and I am using mocks to set some of the structure members.

I am certain I am seeing this error due to a mistake in my code.. I am not experienced enough to see the flaw... yet. :-)

Thank you again for the suggestions and help!!

**Comment by mvandervoord** [comment]
I think I've got it. In your third test, you don't initialize any of the pointers. I think you're assuming that they are going to be zero in this case, but C doesn't guarantee that. So they're pointing at whatever random memory they point at... 

When you run it on gcov, gcov is likely clearing memory for you in order to keep more predictable behavior. When running on other platforms, it's possible the compiler is just making different decisions, or that you're getting lucky and the memory happens to be zero.

In any case, when it's not zero, it's going to assume they are valid and attempt to run them, hence the segfault.

It fixes the bug on my system if I init all three pointers to NULL in test 3.

**Comment by krish2487** [comment]
On the dot. 
Facepalm moment!! :-D

initializing the pointers to null fixed the tests even on my end now.

Again, I cant thank you enough to spend the time helping me . :-)
Thank you @mvandervoord !!!!

**Comment by mvandervoord** [comment]
No problem. I am glad I was able to help out. Best of luck getting into testing! You're off to a good start!
