### ISSUE TITLE
Debug Ceedling with VS Code

### ISSUE THREAD

**Issue by MichaelBMiner** [ThrowTheSwitch/Ceedling#400]
I am just wondering if anyone has gotten ceedling to debug with Visual Studio Code? 

I am even open to other IDEs. I just need to be able to debug into the code so that I can try and solve the issue in my configuration.

**Comment by Letme** [comment]
How is this connected to ceedling? All you need is debugger for your chip/format and its command. IDE is just for graphics... From other threads that is microchip so just use microchip debugger and connect it to simulator (hope that works). Otherwise you can also just run off target (well you need a different compiler and aort some memory/defines...
