### ISSUE TITLE
Ceedling 0.29.0 cannot build projects: UNITY_EXEC_TIME_START and UNITY_EXEC_TIME_STOP not found

### ISSUE THREAD

**Issue by dpostorivo** [ThrowTheSwitch/Ceedling#413]
Just upgraded to ceedling 0.29.0 and there seems to be problems with the time functions:

```
build/test/runners/test_FakeADC_runner.c:61:5: warning: implicit declaration of function ‘UNITY_EXEC_TIME_START’; did you mean ‘UNITY_OUTPUT_START’? [-Wimplicit-function-declaration]
     UNITY_EXEC_TIME_START();
     ^~~~~~~~~~~~~~~~~~~~~
     UNITY_OUTPUT_START
build/test/runners/test_FakeADC_runner.c:76:5: warning: implicit declaration of function ‘UNITY_EXEC_TIME_STOP’; did you mean ‘UNITY_NEW_TEST’? [-Wimplicit-function-declaration]
     UNITY_EXEC_TIME_STOP();
     ^~~~~~~~~~~~~~~~~~~~
     UNITY_NEW_TEST
```
The output file then fails to link due to not finding the symbols:

```
Linking test_FakeADC.out...
build/test/out/c/test_FakeADC_runner.o: In function `run_test':
build/test/runners/test_FakeADC_runner.c:61: undefined reference to `UNITY_EXEC_TIME_START'
build/test/runners/test_FakeADC_runner.c:76: undefined reference to `UNITY_EXEC_TIME_STOP'

```

Is there a known way to disable this feature while examining the root cause?

**Comment by mvandervoord** [comment]
This failure ties directly into another conversation we've been having. It's a mismatch in versions of Unity. `ceedling\vendor\unity` is correctly the newest version, but `ceedling\vendor\cmock\vendor\unity` is lagging in the released gem. 

I'm going to rerelease it today.

A workaround is to just define `UNITY_EXEC_TIME_START` and `UNITY_EXEC_TIME_STOP` to be nothing.

**Comment by mvandervoord** [comment]
Hey @dpostorivo , Would you mind checking something out for me, though? It shouldn't be USING that other version of Unity for anything... and it certainly shouldn't be using the unity_internals.h from one and the unity.h from the other.

If you go into your ceedling gem and actually rename the nested unity project:

```
<ruby root>/lib/ruby/gems/<version>/gems/ceedling-0.29.0/vendor/cmock/vendor
```

That entire vendor directory should not be used by ceedling, because it has its own copy of whatever is needed. I'm curious if you rename that vendor folder to something else if everything still compiles and runs?

Oh, another question: I suspect you're running on an existing project. Was the project created as a gem or locally? (meaning does it have its own version of unity?). Did you run `ceedling upgrade` on the project itself?

**Comment by dpostorivo** [comment]
Project was an as gem and I just upgraded and ran them which hasn't been an issue in the past. There are other issues I'm encountering, some are easier fixes with yaml/variable name changing some seem much more complex that I want to register as separate bugs.  Most seem to be in CMock. 

I can try this solution, but I'll be quite busy till next week so I may not get back to you right away.

**Comment by dpostorivo** [comment]
I tried removing `ceedling-0.29.0/vendor/cmock/vendor`completely and it did not solve the issue. I have some spare time next week, so I'll start digging into this problem more.

This is the biggest blocker on 0.29.0 now for me, but I've found a workaround by adding the following define to my project.yml test defines:

```
    - UNITY_EXEC_TIME_START\(x\)=
    - UNITY_EXEC_TIME_STOP\(x\)=
```

**Comment by dpostorivo** [comment]
Found the root of the issue. Our repos have a local copy of unity_internal for some linters which caused a conflict when built against.
