### ISSUE TITLE
Confusing usage of options_paths

### ISSUE THREAD

**Issue by sanko-oz** [ThrowTheSwitch/Ceedling#421]
I've been struggling with `:options_paths:` for a while now until I finally learned:

With a test file named test_ABC.c and a corresponding options file test_ABC.yml 
running:  `ceedling options:test_ABC test:test_ABC` will always end with:

``rake aborted!
Don't know how to build task 'options:test_ABC' (see --tasks)
vendor/ceedling/bin/ceedling:332:in `block in <main>'
vendor/ceedling/bin/ceedling:319:in `<main>'
(See full trace by running task with --trace)
ERROR: Ceedling Failed``

But running: `ceedling options:test_abc test:test_ABC` works without issues. 

`ceedling options:` expects lower case letteres where as `test: ` is able to detect it and provides an understandable error message:
``ERROR: Found no file 'test_abc.c' in search paths. However, a filename having different capitalization was found: 'test/test_ABC.c'.
rake aborted! ``

**Comment by mvandervoord** [comment]
I agree this should have a better error message and it's something I'll make happen.

Are you sure your real filename was called `test_ABC.yml` and not `test_abc.yml`? I ask because I don't see any force-downcasing going on anywhere... it seems like you would have had to have the name of the file wrong in order to get the error you were seeing?

**Comment by sanko-oz** [comment]
actually you were right.
The problem was the test file naming itself. After I changed the test file name to test_abc.c it work independently of the options file name. I renamed my options file to test_ABC.yml and it still works.
