### ISSUE TITLE
Bad Memory Access 

### ISSUE THREAD

**Issue by Isuresh** [ThrowTheSwitch/Ceedling#437]
Hello,

   bool result = false;
   uint16_t computed_crc;
   
  uint8_t read_data_buffer[SIZE];
  memset(read_data_buffer, 0x00, SIZE);
     
  void* post_crc_start_address = (uint32_t *)APP_START_ADDR;
  void* checksum_start_address = (uint32_t *)APP_CHECKSUM_START;
   
   uint32_t post_crc_length = 
       ((uint32_t)checksum_start_address - (uint32_t)post_crc_start_address);
   
   const uint32_t HMAC_LENGTH_BYTES = 32;
   post_crc_length -= HMAC_LENGTH_BYTES;
   
   crc_hardware_init();
   computed_crc = crc_hardware_accumulate(post_crc_start_address,post_crc_length,CRC16_INIT_VAL);
   crc_hardware_de_init();
   
   const uint16_t storedCRC = *(uint16_t*)(checksum_start_address); 
   if (computed_crc == storedCRC)
   {
     result = true;
     
   }
   
   return result; 
}

I am getting ERROR:  This is often a symptom of bad memory access in source or test code.
  at const uint16_t storedCRC = *(uint16_t*)(checksum_start_address);  Line in above function ,can you please help where i am doing wrong 

Thanks
Suresh

**Comment by mvandervoord** [comment]
Hi Suresh,

It'd be good to know how you have your project.yml configured... specifically what tools you're using. My first instinct is that you're running Ceedling with tests that are running with stock gcc on your host machine. In that case, the error is likely because the memory addresses are those that belong to your embedded space. That same memory address on your mac/windows/linux machine isn't necessarily going to be accessible to you... and it's definitely not going to have the results you want.

If this is your situation, there are two good solutions.

One option (particularly if you have a LOT of memory-specific code like registers, etc) is to switch to using a cross-compiler and a simulator. On the simulator, you're not going to run into this problem because it's going to map all the memory for you.

The second option is to tweak your code a bit here. You could pass IN the addresses for the memory range to read / write and the crc address... allowing you to test it with a memory buffer instead of the fixed range that your embedded processor uses. Alternatively, you can redefine those address to something different during a test, like so:

```
#ifdef TEST
extern uint16_t testable_checksum;
#define APP_CHECKSUM_START (&testable_checksum)
#else 
#define APP_CHECKSUM_START 0x1FFFFFFE // or whatever the real address is
#endif 
```

If I'm on the wrong track, more information about your configuration is going to be needed. :)

**Comment by Isuresh** [comment]
Hi @mvandervoord , 
 
Thank You for your input, I am continuing with the second option.

thanks
Suresh
