### ISSUE TITLE
why `ceedling new project` don't generate a .gitignore file by default?

### ISSUE THREAD

**Issue by dd1994** [ThrowTheSwitch/Ceedling#45]
most people use git for version control， and just like `rails new project` and `bundler gem project`,
they generate a .gitignore file by default, It would be awesome! (sorry for my poor English...)

**Comment by mvandervoord** [comment]
This is a really good idea. If nothing else, it could be a flag that could
be enabled somewhere to always generate that file.

**Comment by zanedp** [comment]
I like the flag idea: Even though a lot of people use git, I'm not sure it's a majority, especially when you consider corporate users.

**Comment by mvandervoord** [comment]
Excellent point, Zane.

**Comment by dpostorivo** [comment]
I'd be down for doing this, however I'd like some input on how others use Ceedling and what exactly they want ignored. For example, the workflow for my company before we completely switched to using the --as-gem option we would always exclude the vendor directory due to it adding a lot of overhead to the repo that could be recreated easily by Ceedling. I'm not sure that's the typical workflow so I'm really curious to hear other's input on this.

As I see it, the build directory should just be excluded by default, however without knowing others workflows that might be too strong of an ignore. I think in the initial try of this I'll just ignore the subdirectories of build which are:

```
build/artifacts
build/gcov
builld/logs 
build/temp
build/test
```
