### ISSUE TITLE
Command hooks do not work with an array of executables

### ISSUE THREAD

**Issue by tonybayley** [ThrowTheSwitch/Ceedling#459]
Ceedling documentation on this page:
https://github.com/ThrowTheSwitch/Ceedling/tree/master/plugins/command_hooks

States that:
You may also specify an array of executables to be called in a particular place, like so:
```yaml
:tools:
  :post_test:
    -  :executable: echo
       :arguments: "${1} was glorious!"
    -  :executable: echo
       :arguments:
         - it kinda made me cry a little.
         - you?
```

This does not work.  An error is thrown: TypeError: no implicit conversion of Symbol into Integer.  My project.yml contains a code snippet similar to this, to trigger two actions via the pre_release hook.  
```yaml
:tools:
  :pre_release:
    - :executable: bash
      :arguments:
        - -c
        - "echo doing pre-release action1..."
    - :executable: bash
      :arguments:
        - -c
        - "echo doing pre-release action 2..."
```

The cause of the error is within Ceedling's function _tools_setup(config)_ in the module _configurator.rb_.  I have included the start of the function below:
```ruby
  def tools_setup(config)
    config[:tools].each_key do |name|
      tool = config[:tools][name]

      # populate name if not given
      tool[:name] = name.to_s if (tool[:name].nil?)
      ...
```

It is the last line of this code snippet that causes the problem. When config[:tools]['pre_release'] is an Array of Hashes, instead of a Hash, tool[:name] is invalid and throws the "TypeError: no implicit conversion of Symbol into Integer."

**Comment by riestmo** [comment]
I get the same error and it's still open. Any plans on fixing this issue?

**Comment by deltalejo** [comment]
Hi @mvandervoord!
I think I can tackle both #459 and #761 for what I propose the following approach:

1. Modify the **beep** plugin so it is configured on its own section in the project configuration file instead of doing so inside the `:tools` section. e.g.:
    ```yaml
    :beep:
      :on_done: :bell
      :on_error: :bell
    ```
    This also could open the possibility to use the `:tools` section to customize the *beep* tool to be used.

3. Modify the **command_hooks** plugin so it has its own configuration section in the project configuration file, inside which hooks tools can be specified following the existing Ceedling tool standard hash, delegating the tools array support to the plugin itself. e.g:
    ```yaml
    :command_hooks:
      :post_test:
        -  :executable: echo
           :arguments: "${1} was glorious!"
        -  :executable: echo
           :arguments:
             - it kinda made me cry a little.
             - you?
    ```

The idea is to avoid modifying Ceedling's core to support special cases for the `:tools` section like **symbol** and **array** and instead make plugins reuse the existing Ceedling capability for tools handling, that it already does well, to setup their own tools according to the plugin purpose.

Let me know your thoughts so I can start working on this.

**Comment by deltalejo** [comment]
Well, probably I'm being a little lazy, because I'm guessing that supporting tools arrays would require to touch various parts of Ceedling's core that rely on tools being a hash, like the compiler or the linker, and I see easier to support tools array just on the **command_hooks** plugin instead of touching here and there the core, but as I've said, I'm just guessing, I don't have so deep knowledge about Ceedling's internals, so possibly you can give me some hints about that.

**Comment by mkarlesky** [comment]
This issue has been resolved with updates to the Command Hooks plugin in the latest prerelease version of Ceedling.
