### ISSUE TITLE
Issue with mock ordering/optimization?

### ISSUE THREAD

**Issue by moonman999** [ThrowTheSwitch/Ceedling#462]
I'm running into a issue attempting to test a function with two function checks in an if statement:

state FunctionA()
{
  if ((CaseA() == GOOD) && (CaseB() == GOOD))
  {
    // go to next state
    state++
  }
  else 
  {
    // remain in current state, retry something
  }
  
  return state;
}

I'm testing this by using mocks:

CaseA_IgnoreAndReturn(BAD);
CaseB_IgnoreAndReturn(GOOD);
FunctionA()
TEST_ASSERT_EQUAL(state, X);

CaseA_IgnoreAndReturn(GOOD);
CaseB_IgnoreAndReturn(BAD);
FunctionA()
TEST_ASSERT_EQUAL(state, Y);

For some reason the second call to FunctionA reacts as if the return value of CaseA and CaseB are both GOOD.  But if I put another check of CaseB inside the if statement:

FunctionA()
{
  if ((CaseA() == GOOD) && (CaseB() == GOOD))
  {
    if (CaseB() == BAD)
    {
       // set state to something that never happens except this case
      state = ERROR;
    }
    else
    {
       state++
    }
  }
  else 
  {
    // remain in current state, retry something
  }
  
  return state;
}

The return value will be ERROR.  It looks like there might be some optimization problems?  

If I only change CaseB values it works fine.  It is only when I try to change CaseA and CaseB together that I have the problem.

i.e. this works:
CaseA_IgnoreAndReturn(GOOD);
CaseB_IgnoreAndReturn(GOOD);
FunctionA()
TEST_ASSERT_EQUAL(state, X);

CaseA_IgnoreAndReturn(GOOD);
CaseB_IgnoreAndReturn(BAD);
FunctionA()
TEST_ASSERT_EQUAL(state, Y);

**Comment by mvandervoord** [comment]
In your first call to `FunctionA`, since you have told CaseA to return `BAD`, it's not going to call CaseB in that if. It's going to immediately drop out. Therefore the CaseB call of `GOOD` that you have queued up is the one that is returned when you reach the second call to `FunctionA`.

You can fix this by either using IgnoreAndReturn instead of ExpectAndReturn (so that you don't care if both are called, just specifying what gets returned if they are called), OR you can split these into multiple tests  so that it catches this sort of bug.

**Comment by moonman999** [comment]
> You can fix this by either using IgnoreAndReturn instead of ExpectAndReturn

I'm not using ExpectAndReturn, I am using IgnoreAndReturn.  Did you mean to say the opposite?

**Comment by mvandervoord** [comment]
No, I didn't. My apologies. I wasn't careful enough.

First, I'd like to say that the best path is to break this up into multiple tests. I think that will both solve your problem AND make it more likely to catch bugs:

```
void test_FunctionA_SHOULD_NotProgressIfCaseABad(void)
{
  CaseA_IgnoreAndReturn(BAD);
  CaseB_IgnoreAndReturn(GOOD);
  FunctionA();
  TEST_ASSERT_EQUAL(state, X);
}

void test_FunctionA_SHOULD_NotProgressIfCaseBBad(void)
  CaseA_IgnoreAndReturn(GOOD);
  CaseB_IgnoreAndReturn(BAD);
  FunctionA();
  TEST_ASSERT_EQUAL(state, Y);
}
```

The problem is this:

When FunctionA gets called the first time, only CaseA is called, because it returns BAD, which makes the `if` statement in `FunctionA` immediately shortcircuit and not call the second portion. (This is how C works... it doesn't bother to run the rest of your if statement on the first sign that it might evaluate to the wrong thing).

When FunctionB gets called the second time, CaseA has [ GOOD ] in its queue and CaseB has [ GOOD, BAD ] in its queue (the first still being left over from the unused first call). It picks the first item off the list and therefore uses GOOD and GOOD, not actually testing the bug you want.

If you break this into two test functions, the CMock queue is cleared between the tests, and the queue will only have BAD in it instead of a leftover value.

An alternative is to add `resetTest` between the two cases.

**Comment by moonman999** [comment]
Understood.  Thanks for the explanation.  Just getting going with Ceedling, so apologies if this was a noob question

**Comment by mvandervoord** [comment]
:) You're all good. Ceedling needs to become more user friendly and this sort of conversation helps me see what is not yet clear.
