### ISSUE TITLE
Ceedling "TEST OUTPUT" section filters the actual test result

### ISSUE THREAD

**Issue by thomasfinchbr** [ThrowTheSwitch/Ceedling#464]
Hi,

I would like to understand the ceedling test report process.
Running this command: ceedling verbosity[4] test:all
I can see the test result print to the stdout after executing the test.
For exemple: UnitTestEeprom.c:123:test_read:PASS

But the section "TEST OUTPUT" only has this:
[UnitTestEeprom.c]
 and some extra info regarding the debugger...

The test result is somehow filtered.
I I must activate the verbosity to level 4 to see the actual test result returned by my debugger.
Why is the test result filtered?

Thanks.

**Comment by mvandervoord** [comment]
By default you have pretty printing enabled when you create a new ceedling project. This will print brief notes of progress, and then a test summary at the end. The test summary will give you the number of tests run, passed, failed, and ignored. In the event of the last two, it will report details... since there are no details of passed tests to print, it doesn't print them. The most common use-case is for people to want to see what has gone wrong, or note that things went just fine. :)

You can look into the ceedling packet documentation to see that there are a number of other output options available if this isn't the report style you enjoy.

**Comment by thomasfinchbr** [comment]
Thanks for your explanation. 
I forced an error and than I could see the output.
I will close the issue.
