### ISSUE TITLE
How to exclude some files and folders from gcov code coverage report?

### ISSUE THREAD

**Issue by ketulbpatel** [ThrowTheSwitch/Ceedling#493]
Hi,

I am not too strong with using gcov and it's a learning process for me along with Ceedling.
I understand the basics of making a code coverage report but not able to exclude certain directories.

I have tried with the following but it didn't work for me.
```
:gcov:
    :report_generator:
      :file_filters: "-../Folder_Name/**"
                      OR
      :file_filters: "-./Folder_Name/**"
                      OR
      :file_filters: "-Folder_Name/**"
                      OR
      :file_filters: "-Folder_Name/*"
```

Thank you!

**Comment by CezaryGapinski** [comment]
I did something similar on the `temp_sensor` example project. I have moved `AdcConductor.[c,h]` from `src` to `src/AdcConductor/src`

Here is my `project.yml` gcov section:
```
:gcov:
  :utilities:
  - ReportGenerator
  :report_generator:
    :file_filters: "-./src/AdcConductor/*"
  :html_report_type: detailed
```
`ceedling gcov:all utils:gcov` command generate html without `src/AdcConductor/src/AdcConductor.c`

Can you show how `Folder_Name` path looks like without exclusion in the final ReportGenerator report?

**Comment by ketulbpatel** [comment]
Thank you @CezaryGapinski  for your response,

Following is the path details:
```
Project
  UnitTest
    Folder_name
    test
    vender
    project.yml
  Src_folder 1
  Src_folder 2
```

Folder_Name path looks like without exclusion in the final ReportGenerator report:

`UnitTest/Folder_Name/DummyFiles/src/dummyfile.c`

**Comment by CezaryGapinski** [comment]
>Folder_Name path looks like without exclusion in the final ReportGenerator report:
> `UnitTest/Folder_Name/DummyFiles/src/dummyfile.c`

That is weird because mine path is always preceded by `./` or `.\` depends on where I'm using Linux or Windows. So my path in the `./build/artifacts/gcov/ReportGenerator/index.htm` on the Linux for my example looks like this (without `file_filters`):
`./src/AdcConductor/src/AdcConductor.c`

Are you using Windows or Linux? For Windows your filter path should be changed from `/` to `\\` and looks like this:

```
:file_filters: "-.\\Folder_Name\\*"
```
or you can also try:
```
:file_filters: "-.\\UnitTest\\Folder_Name\\*"
```

because I do not know exactly your `project.yml` configuration I can only guess.

>Also I have changed report root to:
:report_root: ".."

I think this option is only for `gcovr` and not for `ReportGenerator`.

**Comment by ketulbpatel** [comment]
Still not bale to exclude respective file from gcov code coverage(/HTML) report.

Adding more details:

I am using gcovr, and ReportGenerator is not enabled in project.yml file.
	
```
:gcov:
    :html_report: true
    :html_report_type: detailed
    :html_medium_threshold: 75
    :html_high_threshold: 90
    :xml_report: false
    :report_root: ".."
    :report_generator: # added to exclude file from gcov code coverage report
      :file_filters: "-.\\UnitTest\\Dummy_Files\\*"
```

After running `ceedling gcov:all utils:gcov` command generated report path is as per the following:

` /UnitTest/build/artifacts/gcov/GcovCoverageResults.html`

**Comment by CezaryGapinski** [comment]
>I am using gcovr, and ReportGenerator is not enabled in project.yml file.

It changes a lot, because as you have noticed ceedling gcov plugin uses gcovr or ReportGenerator tool. You should use option specified to `gcovr` what is `:report_exclude:`. You can try these settings:

```
:gcov:
  :reports:
    - HtmlDetailed
  :utilities:
    - gcovr
  :gcovr:
    :report_root: ".."
    :report_exclude: "^vendor.*|^build.*|^test.*|^lib.*|\.\./UnitTest/Dummy_Files/"
```
As you can see, you can omit default values for medium or high threshold (because they are set to 75 and 90 by default), and `xml_report` - it is not used by default.

These settings will work when you have ceedling in version `0.30.0`. You can check your ceedling version by the command `ceedling version`.

**Comment by ketulbpatel** [comment]
Thank you @CezaryGapinski for the prompt reply,

I have upgraded ceedling version to `0.30.0` and after that used above-suggested configurations for gcov, now it works fine.

Did following configurations for Gcov:
```
:gcov:
  :reports:
    - HtmlDetailed
  :utilities:
    - gcovr
  :gcovr:
    :report_root: ".."
    :report_include: "../Application/.*"  #keep only Application folder source files
    :report_exclude: "^vendor.*|^build.*|^test.*|^lib.*"
```
Again, Thank you very much for help and support!

**Comment by jifengtx** [comment]
[
[project.txt](https://github.com/ThrowTheSwitch/Ceedling/files/5626499/project.txt)
](url)
