### ISSUE TITLE
Depreciated plugin style used in gcov. Use new directory structure!

### ISSUE THREAD

**Issue by PrimeraTech** [ThrowTheSwitch/Ceedling#52]
Trying to use the gcov plugin.  No readme file as indicated in the documentation. No gcov data is generated.  The message "Depreciated plugin style used in gcov. Use new directory structure!" is displayed.  Is there a way to enable gcov?

**Comment by UUSim** [comment]
This is just a warning, the plugin should work fine nonetheless. Are you sure you're calling `rake` with the task `gcov:all`?
To print a list of available tasks run `rake -T`.

**Comment by dpostorivo** [comment]
The gcov plugin has been updated since [this commit](https://github.com/ThrowTheSwitch/Ceedling/commit/898cc50cbf0293e27e89cb0b1b4420c0c2879b75) and the warning has been removed since [this commit](https://github.com/ThrowTheSwitch/Ceedling/commit/2bd259a1adf6e23672db1d2fb367740860c03b16) as all the plugins have been updated to the new structure. You should be able to use it with no problem in the latest master commit and maybe soon we can get a new gem release.

**Comment by mvandervoord** [comment]
(It'll definitely be in the next gem release, which should be happening soon)
