### ISSUE TITLE
: multiple definition of `xxx'

### ISSUE THREAD

**Issue by jifengtx** [ThrowTheSwitch/Ceedling#531]
hi，
May I ask, I reported "Multiple Definition" wrong when compiling? How can I solve this problem

**Comment by mvandervoord** [comment]
Hi. 

A common problem that people run into is that they have included both the mock and the real version of a function in the same test. Because C is a static language, only one of them can be included per test... so when you want to TEST that function, you include the real file... and when you want to test another function which USES that function, you include the mock.

If this isn't the issue you're running into, more details would be helpful. If you can paste source code here and let us see what your test looks like, that would be awesome.

**Comment by jifengtx** [comment]
### error message:

gcc.exe "build/test/out/c/TestLedDisplay_runner.o" "build/test/out/c/TestLedDisplay.o" "build/test/out/c/LedDisplay.o" "build/test/out/c/unity.o" "build/test/out/c/cmock.o" -o "build/test/out/TestLedDisplay.out" -lm 2>&1'
> Produced output:
build/test/out/c/LedDisplay.o: In function `AppRedLedInit':
D:\GitHubRoot\EmbeddedV\ax100-sensor\sensor_based_on_platformV\ceedling/../source/Component/app/App_Sensor/HMI/src/LedDisplay.c:28: undefined reference to `HAL_GPIO_Init'
D:\GitHubRoot\EmbeddedV\ax100-sensor\sensor_based_on_platformV\ceedling/../source/Component/app/App_Sensor/HMI/src/LedDisplay.c:29: undefined reference to `HAL_GPIO_Init'

**Comment by jifengtx** [comment]
### .h file definition
`#define CFG_LED_CLK_ENABLE()     __HAL_RCC_GPIOC_CLK_ENABLE()

/*Define the IO structure variable  *********************************************/
static GPIO_InitTypeDef  GPIO_InitStruct;

/*Led red light initializes******************************************************/
#define LED_RED_INIT()                                              \
    do {                                                            \
        GPIO_InitTypeDef GPIO_InitStructure;                        \
                                                                    \
        GPIO_InitStructure.Pin     = GPIO_PIN_11;                   \
        GPIO_InitStructure.Speed   = GPIO_SPEED_FREQ_LOW;           \
        GPIO_InitStructure.Mode    = GPIO_MODE_OUTPUT_PP;           \
        HAL_GPIO_Init(GPIOC, &GPIO_InitStructure);                  \
    } while (0);                                                    \
`

**Comment by jifengtx** [comment]
hi mvandervoord,
The problem I ran into was defining the function in the.h file with the macro, using the.c file with the CEedling to test for errors
**undefined reference to `HAL_GPIO_Init'**
