### ISSUE TITLE
Paths config doesn't handle "./"

### ISSUE THREAD

**Issue by recursify** [ThrowTheSwitch/Ceedling#55]
```
:paths:
  :test:
    - +:test/**
    - -:esp/test/support
  :source:
    - +:./
```

Complains with "ERROR: Config path [:paths][:source][''] does not exist on disk."

I moved project.yml into my main source directory (to keep everything in source control).  It seems like the file path standardization doesn't handle "./" very well.

FilePathUtils.standardize seems to be the culprit

**Comment by mvandervoord** [comment]
Is your rakefile also in ./ ? When you call ceedling, is that where you are calling it from?

**Comment by recursify** [comment]
Correct - I moved the rakefile and project.yml into the same directory (with the src files).

**Comment by mvandervoord** [comment]
Interesting. Out of curiosity, is it ok if you backup and then move forward again (giving it a full relative path like ../projname/)?

**Comment by recursify** [comment]
Ahh - yes, that does work.  It's a good workaround for now.  Yeah just looking at that regex, looks like it was only looking for a single "."

**Comment by mvandervoord** [comment]
Thanks for letting me know. I'll try to get an actual bugfix for this. I'm glad we have a workaround until then. If you notice anything else, please let me know!

**Comment by mvandervoord** [comment]
whew. Ok. I think I have this issue fixed and merged into the main branch. If you have it installed already,  you can update by typing `gem update ceedling`, otherwise use `gem install ceedling`. This will pull down the latest gem.

If you started a project already using `ceedling new projname --as-gem` then I think you are ready to go. 

Otherwise, ceedling is probably still going to report as 0.18 instead of the new 0.19 when you type `rake version`. If this is the case, I think the only option at the moment is to manually replace the vendor directory. We're going to make this easier in the future.

I'd appreciate anyone who can let me know if this update works for them (either way)
