### ISSUE TITLE
Problems with GCoV usage

### ISSUE THREAD

**Issue by jifengtx** [ThrowTheSwitch/Ceedling#557]
hi，
Thank you very much for the powerful tool, I encountered a problem in using it.
In my YAML project ，Import other path YAML project

**project.yaml**
```
:import:
  :confighmi: ../source/Component/app/app_sensor/hmi/config.yml

:paths:
  # :test:
    # - +:test/**
  # :source:
    # - src/**
  :include:
   - +:rtos/inc/*
   - +:rtos/src/*
   - +:MyTest/*
```
**config.yml**

```
:paths:
  :test:
      - ../source/Component/app/app_sensor/hmi/ut/*
  :source:
      - ../source/Component/app/app_sensor/hmi/src/*
      
  :include: 
    - +:../source/Component/app/app_sensor/hmi/inc/*
```
**Generate coverage test report containing test files**
![image](https://user-images.githubusercontent.com/34359893/105826994-6375e480-5ffc-11eb-921b-33aa87eeeff8.png)
### the trouble is 
Can you remove UT test code from coverage report

**Comment by mvandervoord** [comment]
Interesting. Honestly, I'm surprised that the unit test IS part of you test code in this instance. Does this only occur when you have a yaml file including another?

**Comment by jifengtx** [comment]
> Interesting. Honestly, I'm surprised that the unit test IS part of you test code in this instance. Does this only occur when you have a yaml file including another?

Yes, I have tested that this problem only occurs when importing YAML files

**Comment by jifengtx** [comment]
> Interesting. Honestly, I'm surprised that the unit test IS part of you test code in this instance. Does this only occur when you have a yaml file including another?

Can this problem be solved?

**Comment by beckerzito** [comment]
@jifengtx 

A way to solve that is to use a filter directly into the tool you're using to generate the HTML. In your case, it seems to be the GCOVR.

For example, I've faced this issue using ReportGenerator instead of GCOVR, and I could remove these undesired modules from the report, using the filter configuration:
`:file_filters: "-.\\..\\common\\*;-.\\test\\support\\*"`

On the other hand, those filter for GCOVR you can find on the GCOV documentation, in this link: https://github.com/ThrowTheSwitch/Ceedling/tree/master/plugins/gcov

You'll see some way to solve your problems through the configurations:
`# Keep only source files that match this filter. (gcovr --filter).
    :report_include: "^src"

    # Exclude source files that match this filter. (gcovr --exclude).
    :report_exclude: "^vendor.*|^build.*|^test.*|^lib.*"

    # Keep only gcov data files that match this filter. (gcovr --gcov-filter).
    :gcov_filter: <gcov_filter>

    # Exclude gcov data files that match this filter. (gcovr --gcov-exclude).
    :gcov_exclude: <gcov_exclude>

    # Exclude directories that match this regex while searching
    # raw coverage files. (gcovr --exclude-directories).
    :exclude_directories: <exclude_dirs>`

Finally, it's important to note that with this solution you'll be applying the filter only to the report tool. It means that GCOV will still be applied to all those modules, consuming process time and will also appear on the log.

**Comment by jifengtx** [comment]
@beckerzito 
I have tried the method you gave me, but I still can't solve the problem
**project.yaml**

```
:gcov:
  :file_filters: "-..\\source\\Component\\app\\app_sensor\\hmi\\ut\\*"
  # :report_exclude: "^ut.*"
  # :html_report_type: basic
  # :html_report_type: detailed

  
:libraries:
  :system:
    - m

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    # - stdout_pretty_tests_report
    - module_generator
    - xml_tests_report 
    - warnings_report 
    - gcov
...
```

**Comment by jifengtx** [comment]
@beckerzito 
Thank problem has been resolved, the solution is [https://github.com/ThrowTheSwitch/Ceedling/issues/493](url)
