### ISSUE TITLE
Gem version doesn't match Ceedling version

### ISSUE THREAD

**Issue by chris-hammond** [ThrowTheSwitch/Ceedling#562]
When running `gem install ceedling`, the 0.31.0 gem is properly installed, but `ceedling version` reports that the ceedling version is still 0.28.3. This is also true when installing the 0.30.0 gem (i.e. `gem install ceedling -v "<0.31.0"`). Both gems seem to contain the 0.28.3 version of ceeedling.

This has been reproduced both in windows and linux. Here's some outputs from the install testing:

```
$ sudo gem install ceedling
Fetching deep_merge-1.2.1.gem
Fetching constructor-2.0.0.gem
Fetching ceedling-0.31.0.gem
Fetching rake-12.3.3.gem
Fetching thor-0.20.3.gem
Successfully installed thor-0.20.3
Successfully installed rake-12.3.3
Successfully installed deep_merge-1.2.1
Successfully installed constructor-2.0.0
Successfully installed ceedling-0.31.0
Parsing documentation for thor-0.20.3
Installing ri documentation for thor-0.20.3
Parsing documentation for rake-12.3.3
Installing ri documentation for rake-12.3.3
Parsing documentation for deep_merge-1.2.1
Installing ri documentation for deep_merge-1.2.1
Parsing documentation for constructor-2.0.0
Installing ri documentation for constructor-2.0.0
Parsing documentation for ceedling-0.31.0
Installing ri documentation for ceedling-0.31.0
Done installing documentation for thor, rake, deep_merge, constructor, ceedling after 1 seconds
5 gems installed

$ ceedling version
  Ceedling:: 0.28.3
CException:: 1.3.1.18
     CMock:: 2.4.6.217
     Unity:: 2.4.3.122
```

This has been quite frustrating, as version 0.28.3 has very inferior reporting capabilities for gcov.

**Comment by mvandervoord** [comment]
Chris -- my best guess is that if you look at your project file, you'll find that you're using a vendor-installed ceedling instead of the latest gem. If you'd like to switch to the new Ceedling, the best way (at the moment... this is getting improved is to do the following):

Update your project.yml file:

```
:project:
  :which_ceedling: gem
```

If you have `:unity` and/or `:cmock` sections and they have `:vendor_path:` lines, remove them.

If you have a rakefile, this is no longer necessary and it can also be removed.

In the `:plugins:` and `:load_paths:` section, replace `vendor/ceedling/plugins` with `"#{Ceedling.load_path}"`

You should now be using the gem directly... you can remove the folder `vendor/ceedling` from your project once you're sure it's working again.

**Comment by chris-hammond** [comment]
Ah-ha! That did it! Perhaps a message could be added to `ceedling version` to list the path of the ceedling version it is reporting?

In any case, my coverage report is now working!! Awesome. Now my only challenge is that I'm seeing a blast of "Could not find coverage results for..." messages. I'll open a separate issue for that.
