### ISSUE TITLE
using treat_external: :include + treat_inline causes unwanted behavior

### ISSUE THREAD

**Issue by LoPromise** [ThrowTheSwitch/Ceedling#582]
cmock: 
  treat_external: :include
  treat_inline: :include
will cause the original header to be copied over to mocks folder
will check later this day if version issue...

**Comment by mvandervoord** [comment]
The latest versions of CMock do this when using `:treat_inline: :include`. In order to mock an inline function, the original inline version can't be included in the header... so the entire file is copied with the inline body replaced with just a declaration. This file is used for testing instead of the original.

Is it causing a problem for you?

**Comment by LoPromise** [comment]
not really just wanted to know if its intended i think... forgot the problem already. completely agree... was testing header of someone else... I will try to remember what caused it... maybe there a setting needed in some edge cases...
