### ISSUE TITLE
Return results in command prompt

### ISSUE THREAD

**Issue by sliv2001** [ThrowTheSwitch/Ceedling#643]
Hello,
Please, could you add the feature for Ceedling to return "success" to the command prompt? Or, maybe I just have not seen this feature in Ceedling?

Thank you in advance!

**Comment by Letme** [comment]
Like return value 0 vs non-zero or print out success word on the end? Do you have a use case for this?

**Comment by sliv2001** [comment]
Sorry, I've skipped a significant part. 
Yes, like return value 0 vs non-zero. When some of tests fail, Ceedling returns non-zero, so CI server (I use Jenkins) marks whole build as failed. This option might be very useful

**Comment by Letme** [comment]
Let's specify it a bit more. You want Ceedling to return 0 when build was successful and no matter the test run result, or you want it to return 0 even when compilation fails (or even when coverage fails)?

The usecase for proper return values is that you actually do not want failures in your pipeline - let alone mask them. I assume your usecase is because you have some postprocessing, but then some bash magic (like saving an return value to a variable), might be better option - to run postprocessing and then fail the build. So I am interested why you would not like to have a failing build when some tests fail, because Jenkins has some warnings plugin, otherwise you can use command line warnings-plugin (https://github.com/melexis/warnings-plugin) to control number of acceptable failures (technical debt).

**Comment by sliv2001** [comment]
Thank you for your reply.

I would like Ceedling to return 0 only when build, coverage, etc. were successful, though some of tests might be failed. Otherwise there is no point in CI itself. 

Yes, you are right about postprocessing. In fact, I want Jenkins to behave this way because in the project I'm working on some test failures are possible at this point, and failure of one test, ruining all the build, which was compiled successfully, doesn't seem to be the best option.

I'll try to use idea you recommended. Thank you! But I have no idea yet, how to make bash distinguish build failure and test failure.

**Comment by Letme** [comment]
You have option to use junit output and then warnings plugin I pasted you parses that and maintains the number of warnings which you deem acceptable. That way if you have 2 failures, it does not rise to 3, while in your proposal you do not distinguish about regressions. Maybe https://crt.the-mori.com/2020-12-03-number-failing-junit-unit-tests-project-control is a decent start for setup guide.

Your proposal is basically fail only on test run failure, but it will mask when there is more tests that failed than allowed, so ceedling would need to handle a lot more of this.

btw: I am used to splitting compilation (build), test (coverage), static analysis, doc stages in CI. And Ceedling allows you to run just certain tasks.

**Comment by bvtthead** [comment]
Similar to  #174 and #538, I believe.

#644 would change the ceedling exit code to number of test failures.

Let me know if I should pull this issue into that PR.

**Comment by sliv2001** [comment]
Sorry for late answer.
In fact, I've solved my problem by 
1. Adding " & exit /B 0" right after ceedling command 
2. Setting build as failure if test files were not updated.
It works and is enough in my case.
Thanks for your ideas of solution.

@bvtthead , in fact this issue is kind of opposite to those you mentioned: this one would allow Ceedling to ignore test failures and return 0 to ERRORLEVEL variable. As an optional parameter it might be useful allowing to control Ceedling output.
