### ISSUE TITLE
Testing values of local variables before invoking a function.

### ISSUE THREAD

**Issue by mmurty** [ThrowTheSwitch/Ceedling#682]
Hello,
I want a way to test the below function where I want to make sure that the variable txPkt is set with correct values before calling the FMCommWritePkt() function. 
Is there any way I can do that?
Thanks for your time.

```
int8_t FMCommSendRequestAppVersion(void)
{
    fm_comm_pkt_t txPkt = {};
    txPkt.cmdId = FM_COMM_CMD_ID_APP_VERSION;
    txPkt.readWrite = FM_COMM_CMD_TYPE_READ;
    txPkt.payloadLength = FMCommGetPayloadLen(FM_COMM_CMD_ID_APP_VERSION);

    return FMCommWritePkt(&txPkt);
}
```

**Comment by mvandervoord** [comment]
There are multiple ways to do this. You'll want to start by mocking the file that includes `FMCommWritePkt` (it needs to be a different file than the file that contains `FMCommSendRequestAppVersion` ). Now that you have a mock of it, you can set up an expectation for `FMCommWritePkt` and check the argument.

If the structure `fm_comm_pkt_t` is packed and you want to check all of it, you can use the simple method: Just use an expect call with the expected values. For example:

```
void test_FMCommSendRequestAppVersion_SHOULD_ReceiveCorrectData(void) 
{
   FMCommGetPayloadLen_ExpectAndReturn(FM_COMM_CMD_ID_APP_VERSION, 3);
  
   fm_comm_pkt_t expectedPacket = {
     FM_COMM_CMD_ID_APP_VERSION,
     FM_COMM_CMD_TYPE_READ,
     3
  };
  FMCommWritePkt_ExpectAndReturn( &expectedPacket, 0 );

  TEST_ASSERT_EQUAL_INT8( 0, FMCommSendRequestAppVersion() );
}
```

In the case above, we set up an expectation for what we want the entire structure to contain... once that is in place, we call the function being tested. When the mock is called, CMock will verify that it was called with the expected values and return a failure immediately if it has not. 

If `fm_comm_pkt_t` is unpacked and/or you only want to check some fields, you can't use the method above because it may give you false failures on unused bytes. Instead you have two other methods. First is that you can tell CMock how to compare `fm_comm_pkt_t` by writing a custom assertion (This is a beautiful and flexible solution, but outside the scope of a quick answer like this one). The other option is to use a stub and write the check yourself. That might look something like this:

```
int8_t callback_FMCommWritePkt(fm_comm_pkt_t* pkt)
{
   // I've hardcoded the answers, but it could be fancier if you need it to be 
    TEST_ASSERT_EQUAL_HEX8( FM_COMM_CMD_ID_APP_VERSION, pkt->cmdId );
    TEST_ASSERT_EQUAL_HEX8( FM_COMM_CMD_TYPE_READ, pkt->readWrite );
    TEST_ASSERT_EQUAL_HEX8( 3, pkt->payloadLength );
    return 0;
}

void test_FMCommSendRequestAppVersion_SHOULD_ReceiveCorrectData(void) 
{
   FMCommGetPayloadLen_ExpectAndReturn(FM_COMM_CMD_ID_APP_VERSION, 3);
  FMCommWritePkt_Stub( callback_FMCommWritePkt );

  TEST_ASSERT_EQUAL_INT8( 0, FMCommSendRequestAppVersion() );
}
```

This latter solution is going to require you to have these plugins enabled in your project.yml file:

```
:cmock:
  :plugins:
    - :expect
    - :callback
```

Best of luck!

**Comment by mmurty** [comment]
Thanks @mvandervoord for the reply but unfortunately both of these functions are placed in the same source file.
I have tested ``` FMCommWritePkt(&txPkt);``` using mocks, and I was thinking if there was a way to test ```FMCommSendRequestAppVersion(void)``` without re-organizing them.
