### ISSUE TITLE
Problem with func_IgnoreAndReturn

### ISSUE THREAD

**Issue by Karol-coder-20** [ThrowTheSwitch/Ceedling#690]
Hello,
I have no idea why i have this kind of problem:
In code i call 3 times func "mock_QueueSend". Proof:
![image](https://user-images.githubusercontent.com/61209216/179755039-0c978cf0-9c70-4f25-871c-37b3b2dbb1f2.png)
but when i use "Mock_QueueSend_IgnoreAndReturn(0)" something happens with everything and ceedling don't care about anything.
![image](https://user-images.githubusercontent.com/61209216/179755537-0555678f-b43c-45a4-a2a3-eef11a81377a.png)
I know that this describe is general without code but maybe smeone has similar problem.

**Comment by mvandervoord** [comment]
You're getting a failure in the first instance because you said you call QueueSend 3x, but you only set up 2 expectations for it (you call QueueSend_ExpectAndReturn 2x instead of 3x times). Therefore, when your function being tested calls the mocked QueueSend the 3rd time, it notices that you only expected twice, and immediately fails, reporting that it was called more times than expected.

In the second instance, by using IgnoreAndReturn, you're telling CMock that it should NOT count the number of times the function is called. Instead, IF it is called, it should return a 0... otherwise it shouldn't care. It might be called zero times, once, or a million times, and CMock won't have an issue if you tell it to ignore the count. 

Make sense?

(Sidenote: why is it called Mock_QueueSend? There is no need to name the functions you want to mock Mock_... in fact, renaming a function to say that it is going to be mocked defeats the purpose of mocking, which is to directly stand-in for the rest of your code).

**Comment by Karol-coder-20** [comment]
Wow, that was fast. Thank You very much. Now it has sense. i got one extra question.
If i want to take care about first 2 times of this function and ignore third time, ceedling ignores all:
without using "IgnoreAndReturn"(There should be "M" not "A" but i want to show you that test found error):
![image](https://user-images.githubusercontent.com/61209216/179901956-1bb134e3-ff1d-4241-a5a4-64bc85219e84.png)
but when i used "IgnoreAndReturn" ceedling doesn't care about "1 and 2":
![image](https://user-images.githubusercontent.com/61209216/179902103-60745dea-4c3d-44be-9a0c-a1ab0efb646b.png)
so... if i used IgnoreAndReturn even if i declared something before it will ignore all?

(Sidenote: Long story about naming. but U are right. maybe i should change it)

**Comment by mvandervoord** [comment]
Yes, you are correct. Using Ignore invalidates all the calls before it. This isn't how it used to work, but there was a lot of confusion about the ordered rules, so we switched to this a few years ago. Our intention is to add an option for checking a range of calls, but that hasn't been implemented yet.

If things DO get complicated and you want to test for something that doesn't fit the standard built-in calls, you can also use the Stub functionality to write your own mock handling for a particular test. 

Mark

**Comment by Karol-coder-20** [comment]
OKI.

Thank You very much! I am using stub with callbacks too but this issue was some kind of surprice.

I think we could end here ;)
