### ISSUE TITLE
Is it possible to setup Ceedling to compile source code to assembly instead of an executable?

### ISSUE THREAD

**Issue by mamsw** [ThrowTheSwitch/Ceedling#702]
I am likely misunderstanding the provided documentation and use case of assembly code within Ceedling but is it possible during the release task to have a copy of assembly from the source code generate along with the executable aka gcc -S {source file}.

Attempted to specifiy the release assembler tool section in the project file but is not working as expected.

:tools:
  :release_assembler:
      :executable: gcc
      :arguments:
      - "-S ${1}"

Thank you.

**Comment by mvandervoord** [comment]
The `:release_assembler:` section is for compiling assembly files as part of the release process. It's not what you're looking for.

If you wanted assembly *instead* of your binary, you'd replace `:release_linker:`. Because you want to add a new step, you'll want to enable the `command_hooks` plugin and add a `:post_release` step.

**Comment by mamsw** [comment]
Thank you for the direction and this great build system.
