### ISSUE TITLE
preprocessed files gets wrong includes

### ISSUE THREAD

**Issue by informatimago** [ThrowTheSwitch/Ceedling#796]
We have two problems with preprocessed files:

First the simple one: the order of #include in the preprocessed files is reversed.
This comes from `PreprocessinatorFileHandler#preprocess_file` that uses:
```
      includes.each{|include| contents.unshift("#include \"#{include}\"")}
```
   We can easily correct it with:
```
      includes.reverse.each{|include| contents.unshift("#include \"#{include}\"")}
```
The order of includes is important, since they may be implicit
dependencies between them.  It's not clean, but I've never seen a
project without such cases. (And sometimes justified).

Next, we have the more fundamental problem: the general process of
preprocessing files consists in collecting all the `#include` first,
then preprocessing the source, and then extracting from the
preprocessed file, the lines that came from the source, ie. in
particular, removing the `#include` that may happen in the middle of
the file.  This will break a lot of projects.

We may often see cases such as:

```
#include <system-headers.h>
#include "project-components.h"

stuff 1 …

#define SOME_PARAMETER FOO
#define SOME_MACRO(x) first_stuff(x)
#include "parameterized_include.h"
#undef SOME_PARAMETER

stuff 2 …

#define SOME_PARAMETER BAR
#define SOME_MACRO(x) another_stuff(x)
#include "parameterized_include.h"
#undef SOME_PARAMETER

stuff 3 …
```

The preprocessing process will produce:

```
#include "parameterized_include.h"
#include "project-components.h"
#include <system-headers.h>

stuff 1 …

stuff 2 …

stuff 3 …
```

So the whole process needs to be rethought out.
At least, using `includes.reverse.each` should be done immediately.

Relevant issues:
https://github.com/ThrowTheSwitch/CMock/issues/407
https://github.com/ThrowTheSwitch/Ceedling/issues/678
and the general problem of how sources and includes are processed,
which is different than how C compilers process them. See:
https://github.com/ThrowTheSwitch/Ceedling/issues/783

**Comment by mkarlesky** [comment]
The ordering problem of `#include` statements has been fixed in the version 0.32 branch. Preprocessing itself is also undergoing a major refactoring (along with much of Ceedling itself). Perhaps someday Ceedling will include a fully featured C code preprocessor that allows us to extract all the necessary goodness to properly preprocess tests and accompanying files. Until then, the best we can do is make the best possible use of gcc's preprocessor output, knowledge of our tests by convention, and some other educated guesses. It's yet to be seen how much better we can make preprocessing of test files. I can say that version 0.32 now has a much more robust ability to reliably extract #include statements as needed. Unfortunately, try as we might, without a dedicated preprocessing tool, even here, it's not 100% perfect. But, we are making up for this with other features that can help fill gaps in other ways. We'll see where we end up with preprocessing of test files themselves.
