### ISSUE TITLE
Fail to recognize my source & header files.

### ISSUE THREAD

**Issue by kafkaaaa** [ThrowTheSwitch/Ceedling#834]
I'm sorry for frequently posting questions.

I know this isn't a great way,
but honestly I'm tired of continuing to create modules and setting up `project.yml` and paths.

So I'm integrating it into one `ceedling module:create[name]`

But there are some problems. 🥲

---
when I do
`$ ceedling files:source` 
```
source files:
 - ../basic/foo/bar1.c
 - ../basic/foo/bar2.c
 - ../basic/foo/bar3.c
...
file count: 24
```

`$ ceedling files:include`
```
include files:
 - ../myHeader1.h
 - ../myHeader2.h
 - ../myHeader3.h
 - ../util/myHeader4.h
 - ../util/myHeader5.h
 ...
 file count: 93
 ```

---
### project.yml
```
---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: TRUE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
#  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.1
  :default_tasks:
    - test:all

#:test_build:
#  :use_assembly: TRUE

#:release_build:
#  :output: MyApp.out
#  :use_assembly: FALSE

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - +:src/**
    - +:../basic/**/**
  :support:
    - test/support
  :libraries: []
  :include:
    - +:../util/**
    - +:../**

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
    - LINUX
    - _XOPEN_SOURCE
    - _POSIX_C_SOURCE=200809L
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

# Add -gcov to the plugins list to make sure of the gcov plugin
# You will need to have gcov and gcovr both installed to make it work.
# For more information on these options, see docs in plugins/gcov
:gcov:
  :reports:
    - HtmlDetailed
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: 
    - m   # math library
    - rt  # for CLOCK_REALTIME
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - xml_tests_report
...

```
---

### Testing Environment
```
Ubuntu 22.04.3
VSCode Extension: Ceedling Explorer

Ceedling:: 0.31.1
Unity:: 2.5.4
CMock:: 2.5.4
CException:: 1.3.3
```

`$ tree -a`

```
.
├── build
│   ├── artifacts
│   │   └── test
│   │       └── report.xml
│   ├── logs
│   ├── temp
│   └── test
│       ├── cache
│       │   ├── defines_dependency.yml
│       │   ├── input.yml
│       │   └── test_xxx.c
│       ├── dependencies
│       │   ├── CException.d
│       │   ├── cmock.d
│       │   ├── force_build
│       │   ├── test_xxx.d
│       │   ├── test_xxx_runner.d
│       │   └── unity.d
│       ├── mocks
│       ├── out
│       │   ├── asm
│       │   ├── c
│       │   │   ├── CException.o
│       │   │   ├── cmock.o
│       │   │   ├── test_xxx.o
│       │   │   ├── test_xxx_runner.o
│       │   │   └── unity.o
│       │   └── test_xxx.out
│       ├── preprocess
│       │   ├── files
│       │   │   └── test_xxx.c
│       │   └── includes
│       │       └── test_xxx.c
│       ├── results
│       │   └── test_xxx.fail
│       └── runners
│           └── test_xxx_runner.c
├── project.yml
├── src
└── test
    ├── support
    │   └── .gitkeep
    └── test_xxx.c
```
(relative path of project.yml)
my header file path is like `../util/foo.h`   and   `../bar.h`  
my source file path is like  `../basic/foo/bar.c`    and    `../basic/bar/foo.c`

---

It seems normal, but **why ceedling cannot recognize my source & header files??**
(undefined reference to 'my_function')

I would really appreciate it if you could tell me the **cause and how to resolve** that problems.

++
And why there is a error ?  (but it works,  That is an eyesore)
Should I add Include path on VSCode like
`/var/lib/gems/3.0.0/gems/ceedling-0.31.1/vendor/unity/src/` ? 
(This way, the red line disappears)
![image](https://github.com/ThrowTheSwitch/Ceedling/assets/20926959/5873dc30-0ba6-4b62-a8d4-66a475a6b19e)

**Comment by Letme** [comment]
Your image is missing `util/` and `basic` folder (I assume in `src`)? But why do you include a path `../` as prefix? I mean `project.yml` should be in the root of the project you are building (running), so that way you can have some easy includes. I hope you have standard `#include "filename.h"` without path prefixes.

As for VSCode, yes you will need to configure include paths for it's parser to make this work. Not sure if there is a way for VSCode to autodetect this from ceedling.

**Comment by kafkaaaa** [comment]
Thank you for your reply.
I apologize in advance because I'm a beginner in this field.

I have a lot of source files and headers so, I'm trying without copying files to the `src` folder. 
And because my `util` and `basic` folder is on outside of `project.yml` directory
so I use `../` 
Is this the cause?

---

Yes It works if I include like below in my `/test/test_myTest.c` file...
```
#include "../basic/foo/bar.c"
#include "../basic/foo2/bar2.c"
...
```

But the reason why I question this issue is..
Why `:path:` `:source:` `:include:` in `project.yml` doesn't work correctly.

It still doesn't make sense to me.

---

And I got it VSCode's `c_cpp_properties.json` "includePath" problem.
The question I added at the end will be off the table.

**Comment by Letme** [comment]
Your relative includes are the problem (not sure why you are including source files in your test file - but that is a side discussion).

What you want is all files in src folder (even if you have components). I think ceedling was designed by having project.yml in the root, so you going out of scope of project to search for files might be the problem. I also hope that your outside sources have normal includes (not relative), because if they are relative, then include paths are a lot harder to figure and skip (what you do in tests), so I would generally advise against them as a best practice.

In `test_myTest.c` only include header files from components and header file mocks (which you want mocked). The linking and matching is done automatically by Ceedling.

**Comment by mvandervoord** [comment]
It appears from your notes above that Ceedling is finding a lot of files already. What files is it unable to find? Or, more specifically, what folders are the files in that are being missed by Ceedling?

For the second error that you post above, related to VSCode: Just because you've configured Ceedling to know where something is, doesn't mean VSCode knows anything about it. VSCode has its own project concept that doesn't understand anything about Ceedling... so if you want it to know about paths, you have to instruct it separately.

**Comment by kafkaaaa** [comment]
@mvandervoord 
Of course as I've already said It seems normal because
`ceedling files:include` `ceedling files:source` `ceedling paths:include` `ceedling paths:source`
print my legacy files that I want to test.
 
But when I do `ceedling test` , It cannot recognize my header & C files. (That files are not in /src/  and my src folder is empty) 
what folders are the files in that are being missed by Ceedling? --> just one level above `project.yml` directory 

e.g. `tree -a`
```
├── basic
│   ├── common
│   │   └── xxx.c
│   ├── abcd
│   │   └── xxx.c
│   ├── io
│   │   ├── xxx.c
│   │   ├── xxx.c
│   │   ├── xxx.c
│   │   ├── xxx.c
│   │   └── xxx.c
│   ├── net
│   │   ├── xxx.c
│   │   ├── xxx.c
│   ├── os
│   │   ├── xxx.c
│   │   ├── xxx.c
│   │   └── xxx.c
├── xxx.h
├── xxx.h
├── xxx.h
├── xxx.h
├── myModuleName
│   ├── build
│   │   ├── artifacts
│   │   │   └── test
│   │   ├── logs
│   │   ├── temp
│   │   └── test
│   │       ├── cache
│   │       │   ├── defines_dependency.yml
│   │       │   ├── input.yml
│   │       │   └── test_xxx.c
│   │       ├── dependencies
│   │       │   ├── CException.d
│   │       │   ├── cmock.d
│   │       │   ├── force_build
│   │       │   ├── test_xxx.d
│   │       │   ├── test_xxx_runner.d
│   │       │   └── unity.d
│   │       ├── mocks
│   │       ├── out
│   │       │   ├── asm
│   │       │   ├── c
│   │       │   │   ├── CException.o
│   │       │   │   ├── cmock.o
│   │       │   │   ├── test_xxx.o
│   │       │   │   ├── test_xxx_runner.o
│   │       │   │   └── unity.o
│   │       │   └── test_xxx.out
│   │       ├── preprocess
│   │       │   ├── files
│   │       │   │   └── test_xxx.c
│   │       │   └── includes
│   │       │       └── test_xxx.c
│   │       ├── results
│   │       └── runners
│   │           └── test_xxx_runner.c
│   ├── project.yml
│   ├── src
│   └── test
│       ├── support
│       └── test_xxx.c
├── xxx.h
├── xxx.h
├── xxx.h
├── util
│   ├── xxx.h
│   ├── xxx.h
│   ├── xxx.h

29 directories, 140 files
 ```

**Comment by mvandervoord** [comment]
I don't believe your bugs have anything in common. In their case, they're hoping that Ceedling can figure out where system files are without specifying a full or relative path. That's not really something Ceedling knows how to do. It would require it to fetch it from the compiler somehow.

In your case, I think you're just misusing the double-splat specifier `**`. In your example, you're fullying specifying paths, but then adding a double-splat to it. The `**` means "any number of nested directories under this." But you're not expecting it to find the nested directories under it at all (in fact, it'd cause further problems because it'll also want to use your build directories because you've included those).

Try this instead:

```
:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - +:src/
    - +:../basic/**
  :support:
    - test/support
  :libraries: []
  :include:
    - +:../util/
    - +:../
```

**Comment by kafkaaaa** [comment]
Hello, thank you for your continued assistance.

No, doesn't `**` mean it includes all subdirectories?
The commands `$ ceedling files:include` and `$ ceedling files:source` accurately output the files I want to test.
If `**` is the real cause, shouldn't the file list be missing or non-existent when I perform ceedling commands like the ones mentioned above? I'm having trouble understanding.

I've tried your suggestion in `project.yml`, but the issue persists.
In my `/test/test_xxx.c` file, I have to write dozens of `#include "../basic/foo/bar.c"` statements, or else the functions cannot be found.

When I first encountered Ceedling, I copied it to the `src` folder and manually modified include paths for legacy files one by one. However, it was inconvenient, prompting me to ask this question.

To reiterate, coming back to the problem, do I have to write dozens of statements like `#include ../foo/bar.c` in my `test/test_xxx.c` file? Can't this be resolved through the `project.yml` settings? That's my question.

-------
Thank you for your ongoing help.

**Comment by mvandervoord** [comment]
Ah!

I understand what you are saying now. 

This is actually the intended behavior. Specifying the paths in the `project.yml` file tell Ceedling where it can find all the files. But it doesn't tell Ceedling which files are desired for each test.

Specifying the header files in the tests themselves tells Ceedling what files you want to include in the build. For each header, it will include the corresponding source file, if it exists.

The problem you're running into is a problem of dependencies: One source module is calling functions or needing variables from another source file, which requires another source file, and another... eventually you're including a lot more files than you really intend. Yes?

The solution is to use mocks or stubs. Let's look at an example:

Let's say you have three C files, each with a header file. Functions in `A.c` call functions in `B.c` which call functions in `C.c`. 

The test `TestC.c` is easy to write... you just include `unity.h` and `C.h` and you're ready. Ceedling would see these and include `TestC.c`, `C.c`, and `unity.c`. It had no other dependencies.

But let's look at `TestA.c`. You'd tell the test to include `A.h` and `unity.h`. But when it attempts to compile it, it complains that it can't find functions or variables that exist in `B.c`... so you include that... but then THOSE functions call functions or variables from `C.c`... so you include that too... It's a real problem.

Instead, make `TestA.c` include `A.h`, `unity.h` and `MockB.h`. This tells Ceedling that instead of including the real B, you want to include a mock version of B while you're testing A. It breaks the problem chain. It gives you the ability to specify how you would interact with A, without caring how B or C work.

Make sense?

Google "mocking" and "interaction testing" and you'll probably find a lot of examples of this.

Does this make it more clear?

**Comment by kafkaaaa** [comment]
I have been under the impression that specifying header file paths in the `:include` section of the `project.yml` 
is same as `gcc -I` option. So these two things are different, right?

Additionally, thank you for the excellent examples and explanations regarding mocks. Legacy projects, like the one I am currently unit testing, often have intricate dependencies. I will study about mocking.

Initially, I tested with multiple modules, but my supervisor instructed me to consolidate them into one test_xxx.c file. As I try to proceed with this approach, I encounter the issues mentioned earlier. 

Anyway, I'm off to include dozens of header files. Thank you!

**Comment by mvandervoord** [comment]
Yes, the `:include` section does automatically become the `-I` section when using gcc. A `gcc -I` call tells gcc where to find headers, and not which headers to include for each module compiled. In those cases, it still relies on the module writer to specify the includes.

I hate to be the one to disagree with your supervisor, but as one of the developers of these testing tools, I can say with confidence that, most likely, your supervisor is wrong. Unity (and therefore Ceedling) are designed to build a test per C module to be tested. There ARE rare instances where you might want more than one C module to be tested together. But most often, they are meant to test independently. This gives you the most control of the unit that you're testing and the greatest ability to evaluate its performance. It also avoids the problem you're running into now.

If you're using a tool like Ceedling, it's already managing as many test executables as you care to throw at it...

In any case, best of luck.

**Comment by kafkaaaa** [comment]
Thank you. I really appreciate it. I totally agree with you.
