### ISSUE TITLE
Can't mock "wrapper" header file

### ISSUE THREAD

**Issue by DanieleNardi** [ThrowTheSwitch/Ceedling#843]
Hello,
I'm starting a new project with a MSPM0 microcontroller from TI and I'd like to mock the drivers provided by TI for such device.
So far so good with most of the drivers, except the timers management driver: this driver, dl_timerg.h, includes a more general driver, dl_timer.h, and contains a set of typedefs and #defines which simply are aliases of elements of the general driver.
For example, where dl_timer.h declare a function `void dl_timer_doSomething()`, dl_timerg.h contains a `#define dl_timerg_doSomething() dl_timer_doSomething()`. Last but not least, dl_timer.h has an #ifdef barrier conditioned on whether the dl_timerg.h is part of the project or not. With those constraints, I didn't find a way to proper mock these headers.

MSPM0 SDK can be found [here](https://www.ti.com/tool/MSPM0-SDK?keyMatch=MSPM0%20SDK).

To overcome the structure of dl_timerg.h, I tried to mock only dl_timer.h, but this way the linker use the original dl_timer.h instead of the mocked one, so the test can't run properly.
Of course, dl_timer.h contains almost only static inline functions.

My project.yaml file is the following:
```
---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
#  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.1
  :default_tasks:
    - test:all

#:test_build:
#  :use_assembly: TRUE

#:release_build:
#  :output: MyApp.out
#  :use_assembly: FALSE

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
    - C:\ti\mspm0_sdk_1_20_00_05\source\ti\driverlib
    - Debug/syscfg
  :support:
    - test/support
  :libraries: []
  :include:
      - C:\ti\mspm0_sdk_1_20_00_05\source
      - C:\ti\mspm0_sdk_1_20_00_05\source\third_party\CMSIS\Core\Include

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines [__MSPM0L1306__]
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST
    - ti_dl_dl_timerg__include

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
    - :expect
    - :expect_any_args
    - :array
    - :return_thru_ptr
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8
  :treat_inlines: :include

# Add -gcov to the plugins list to make sure of the gcov plugin
# You will need to have gcov and gcovr both installed to make it work.
# For more information on these options, see docs in plugins/gcov
:gcov:
  :reports:
    - HtmlDetailed
    - Cobertura
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []    # for example, you might list 'm' to grab the math library
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov
    - compile_commands_json
    # - html_test_report
    - xml_tests_report
...
```
How to replicate this issue: create a new project with CCS12 targeting an MSPM0 microcontroller, for example MSPM0L1306, configure it with Syscfg (available as CCS plugin), then create a ceedling project into CCS project folder, create a module called "pwm" as follows:
pwm.c
```
include "pwm.h"
#include "ti_msp_dl_config.h"
#include "ti/driverlib/dl_timerg.h"

void func()
{
    DL_TimerG_isPowerEnabled(DO_PWM_MOTOR_INST);
    return;
}
```
pwm.h
```
#ifndef PWM_H
#define PWM_H

void func();


#endif // PWM_H
```
test_pwm.c
```
#ifdef TEST

#include "unity.h"

#include "pwm.h"
#include "mock_dl_timerg.h"
#include "mock_dl_timer.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_pwm_NeedToImplement(void)
{
    DL_Timer_isPowerEnabled_ExpectAnyArgsAndReturn(true);
    func();
}

#endif // TEST
```

This way ceedling returns the error message
```
ERROR: Test executable "test_pwm.out" failed.
> Produced no output to $stdout.
> And exited with status: [0] (count of failed tests).
> This is often a symptom of a bad memory access in source or test code.

rake aborted!

C:/Ruby30-x64/bin/ceedling:25:in `load'
C:/Ruby30-x64/bin/ceedling:25:in `<main>'
Tasks: TOP => build/test/results/test_pwm.pass
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.
```
If you debug step by step this test, you'll find that you will enter the real implementation of DL_Timer_isPowerEnabled instead of its mocked twin.

Thank you very much for any suggestion

**Comment by mvandervoord** [comment]
You've done a great job of documenting the issue. I really appreciate that. I don't have the time at the moment to run your example directly, but I have a guess as to your error, and I have a philosophy of how best to handle these situations. 

Philosophy:

The root problem you're running into is a common one: one where headers aren't really "standalone" without depending on other headers for information... this is particularly common in complex API's.

If the API is complex enough, the easiest thing to do is to create your own header files that has just the types and functions that you care about. You can then use that instead of directly calling the original headers. Let's say we made such a header `timer_api.h`:

```
#ifndef TEST
// When we're not testing, just include the original headers
#include "dl_timerg.h"
#include "dl_timer.h"
#else
// we can still include headers to grab types.
// we put function prototypes here to be mocked.
// we can even put function prototypes here for things that are macros in the real API!
#endif
```

Now, in both your release code and your test code, include `timer_api.h` instead of using the individual timer files. It's easily mockable (a win for tests) and it serves as documentation for what parts of the complex API you are actually using (good for maintenance). It also protects you against API changes if those header files are upgraded or settings are changed. If the API changes below, you now potentially have the option to update the abstraction in one place (this wrapper file) instead of everywhere it is called.

The Error Ceedling is Giving You:

It is possible that the error you're seeing is exactly what you've said... a mismatch in what is getting used in two different places. Most often, though, these mismatches will fail to compile or link completely. It's rarely a runtime error. 

Is `DL_TimerG_isPowerEnabled` a macro that directly passes through to `DL_Timer_isPowerEnabled`? If so, I'm not seeing how this could cause a crash. You're pulling in the mock of both headers, so it's going to create a fake version of `DL_Timer_isPowerEnabled`... The macro `DL_TimerG_isPowerEnabled` remains unchanged, so it will still want to call `DL_Timer_isPowerEnabled`. When linked, the `DL_Timer_isPowerEnabled` it is connected to is the one that has been mocked, because otherwise there would be a conflict of multiple definitions. Your expectation would be the correct one and everything should pass.

My suspicion would be that `DL_Timer_isPowerEnabled` does more than just pass the call along to the next step, and perhaps that's what's failing. I'd be doubly suspicious of anything that uses a pointer (these API's often like to pass around handles, etc). There's a good chance that a handle is being dereferenced or something when it has never been initialized.

In any case, best of luck. I hope this helps.

**Comment by DanieleNardi** [comment]
Thank you very much for the suggestion!

To answer your question, yes, `DL_TimerG_isPowerEnabled` is a macro to `DL_Timer_isPowerEnabled`, which is static inline. Is there a way in project.yaml to tell the linker which file to get?

**Comment by mvandervoord** [comment]
Ceedling automatically knows which file to use based on your test. You included the mocked header, so it knows to use the mocked C file for the test, not the normal C file. If you included both the mock and unmocked header, it would attempt to pull in both and it would fail.

I think we found the problem, though! `DL_Timer_isPowerEnabled` is static inline! So even though you're properly mocking this interface, the `func` call has already flattened the static inline to the things it actually does and doesn't believe there is anything to call there (Oh C... you're painful sometimes!). 

Are you able to modify either of these files? If not, your only option is the long API explanation I wrote above. If you CAN tweak these files slightly, maybe you want to change `inline` to INLINE. Then use this:

```
#ifdef TEST
#define INLINE
#else 
#define INLINE inline
#endif
```

This will make it so that the function isn't inlined during tests and you can mock it properly.

**Comment by DanieleNardi** [comment]
> Ceedling automatically knows which file to use based on your test. You included the mocked header, so it knows to use the mocked C file for the test, not the normal C file. If you included both the mock and unmocked header, it would attempt to pull in both and it would fail.
> 
> I think we found the problem, though! `DL_Timer_isPowerEnabled` is static inline! So even though you're properly mocking this interface, the `func` call has already flattened the static inline to the things it actually does and doesn't believe there is anything to call there (Oh C... you're painful sometimes!).
> 
> Are you able to modify either of these files? If not, your only option is the long API explanation I wrote above. If you CAN tweak these files slightly, maybe you want to change `inline` to INLINE. Then use this:
> 
> ```
> #ifdef TEST
> #define INLINE
> #else 
> #define INLINE inline
> #endif
> ```
> 
> This will make it so that the function isn't inlined during tests and you can mock it properly.

This solution works, but now a new issue has entered: I get some assembler errors, die to the fact that the CMSIS included in the SDK adds some __ASM which is not recognized by the native GCC, so now I have ti find a way to workaround the cmsis_gcc.h. I guess the proper way is to compile with ARM GCC and run unit test directky on chip or a simulated environment (QEMU?). Do you have any suggestion?

**Comment by mvandervoord** [comment]
Yes. You can run on QEMU and it'll solve this particular issue. It'll also have the benefit of testing using the same compiler your release uses, etc.

The alternative is still to build an API file as I described above, which avoids the entire CMSIS layer altogether.

Either will work. They have pros and cons and it's really a matter of preference.

**Comment by DanieleNardi** [comment]
> Yes. You can run on QEMU and it'll solve this particular issue. It'll also have the benefit of testing using the same compiler your release uses, etc.
> 
> The alternative is still to build an API file as I described above, which avoids the entire CMSIS layer altogether.
> 
> Either will work. They have pros and cons and it's really a matter of preference.

Thank you very much!
