### ISSUE TITLE
Test Case Naming Convention

### ISSUE THREAD

**Issue by swaldhoer** [ThrowTheSwitch/Ceedling#850]
I took me something like 20 minutes to realize why the test case
 
```c
extern void testMyTest(void){}
```
 
wouldn't run although on first sight it looks like it fulfills the requirements defined in [Convention for Test Case Functions + Test Runner Generation](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/CeedlingPacket.md#convention-for-test-case-functions--test-runner-generation).
 
However, it seems to be invalid to explicitly specify the function scope via `extern`.
 
I would not call it a typical bug, but this behavior was quite unexpected.
Maybe both
 
- `extern void testMyTest(void)` and
- `void testMyTest(void)`
 
should be valid ways to specify a test function.

**Comment by swaldhoer** [comment]
> No way. Read more about `extern` and put it only where and when it is needed. It will be a good lesson in C.

Telling someone "you are absolutely wrong" and using "read something, but I won't tell you what" as an explanation is not only rude, but also not helpful. Therefore, could you please provide an actual link with information backing up whatever you are trying to tell me? I'm happy to learn.

> `extern` is not even to be abused in header files of compilation units for declarations, which are accessible. It is only to be used when something is to be exposed and implemented out of scope. So practically, `example.h` should not have `extern` for functions defined in `example.c`.

Your statement is a little vague and your are not detailing your example in a good way, but depending on how you mean it, it could be wrong.
If a function is declared in `example.h`, than only because **external linkage is required** (and then `extern` can optionally be used as storage-class specifier). Otherwise, i.e., if external linkage is **not** required, then the function shall be declared and defined with the storage-class specifier `static` in `example.c`. Using or omitting `extern` is up to the user as the default linkage is external (specified by the standard in the storage-class specifier related sections).

Maybe you have access to the [MISRA-C](https://misra.org.uk/misra-c/) guidelines, which also describes the use of `extern`, and backups the example I used above.

**Comment by Letme** [comment]
I have never seen such example, even if you quote MISRA for usage of "extern" (although read newer MISRA to get more details what they really meant).

example.h has extern keyword, which is useless in this case in header file:
```
extern void testFunc(void);
```
This is called declaration, so you declared this function is external to the compilation unit. Since example.h is included in many files, this seems quite strange to declare especially if you provide definition for this function along with it (not that user has to make his/her own definition)

Then `example.c` has following without `extern`:
```
#include "example.h"

void testFunc(void)
{
    // bla
}
```

I have never seen source file with extern keyword like you noted above:
```
#include "example.h"

extern void testFunc(void)
{
    // bla
}
```

So maybe since you know MISRA you are more experienced than what I expected, but how would you/compiler read this chunk of code? This function is external to this compilation unit, but here it is defined? So is it external or not?

**Comment by mkarlesky** [comment]
@swaldhoer Could you say more about how you are arranging your test cases that inspired the use of `extern`? Are you, for instance, trying to arrange multiple tests suites with certain test cases in common? The typical Ceedling test suite comprises multiple test executables where each test executable maps to / is built from a single C file of test cases.

**Comment by swaldhoer** [comment]
There was nothing specific that needed it, but as it does not make a difference to define the function with or without `extern` I just wondered, why it did not get correctly parsed as a test function.
But we'll just define all test functions without `extern` as this just works.
