### ISSUE TITLE
GCOV at test/ceedling_0_32_rc

### ISSUE THREAD

**Issue by claudiiolima** [ThrowTheSwitch/Ceedling#852]
I start to test the `test/ceedling_0_32_rc` branch and when I try to run gcov plugin, `ceedling gcov:all`, during the objects building process, rake does not recognize build task:

Log:

```bash
Determining Artifacts to Be Built...

Building Objects
----------------
RuntimeError ==> Don't know how to build task 'test_converter_properties+build/gcov/out/test_converter_properties/test_converter_properties.o' (See the list of available tasks with `rake --tasks`)
```

> NOTE: The same process using task `ceedling test:all`, works as expected.

**Comment by mkarlesky** [comment]
Hi, @claudiiolima. Thanks for testing out the release candidate of 0.32 and sorry for this glitch.

I can't replicate what you're seeing. Which of the various pre-release builds of 0.32 are you using? Could you provide your project file?

**Comment by claudiiolima** [comment]
I am using 0.32.0-4e4c66b rc, tomorrow I will publish here the project file and the full output command

**Comment by claudiiolima** [comment]
[project.log](https://github.com/ThrowTheSwitch/Ceedling/files/14418776/project.log)
[input.yml](https://github.com/ThrowTheSwitch/Ceedling/files/14418780/input.txt)

I modify some at `input.yml` to hide some sensitive information, some assume the text with `?` are filled correctly

**Comment by claudiiolima** [comment]
![image](https://github.com/ThrowTheSwitch/Ceedling/assets/20281895/b6fc4cef-b254-4c9e-95b0-d630438e8a41)

I try to check all details objects to compare with the same object during `test:all`, seems to be the except the build path, as expected.

![image](https://github.com/ThrowTheSwitch/Ceedling/assets/20281895/a9424426-a87f-4267-8d50-326b27a11072)

**Comment by mkarlesky** [comment]
@claudiiolima Thank you for sending all this. This has really got me stumped. The two projects we use to validate Ceedling — one simple and one quite sophisticated — run with `gcov:all` just fine.

I can't think of anything that would break the Rake rule that is executing compilation for the .o file. It's quite a simple linkage, and the rake Rule itself hasn't changed from the last version of Ceedling. I even tried replicating your project structure with the same directories and test file names. Everything worked fine.

I had an idea that it might have been due to a versioning conflict of old and new Ceedling, but I quickly disproved that idea.

Questions:

1. Does this happen for any test run individually with `gcov`? What happens if you run `ceedling gcov:test_converter_properties` and what happens for any other test that is not `test_converter_properties`?
1. How did you install the pre-release version of 0.32? Gem install? Downloading the repo and running it directly? How were you running the previous version?

**Comment by claudiiolima** [comment]
@mkarlesky Thanks for the help and comments, I discovered what was messing up some things, it was an old plugin that I was using to merge YML files, when I merged these files manually and discarded the old plugin, everything worked fine

@deltalejo thank you too.
