### ISSUE TITLE
undefined method `exists?' for class File (NoMethodError) when run ceedling new project on UBuntu on wsl2

### ISSUE THREAD

**Issue by MarvelousJade** [ThrowTheSwitch/Ceedling#865]
![PixPin_2024-03-24_07-16-20](https://github.com/ThrowTheSwitch/Ceedling/assets/162636625/83bf3edb-5beb-4c64-820e-ea0b1b0a1a44)

ceedling new project

/home/user/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.31.1/bin/ceedling:12:in `<top (required)>': undefined method `exists?' for class File (NoMethodError)

  project_found = File.exists?(main_filepath)
                      ^^^^^^^^
Did you mean?  exist?
        from /home/user/.asdf/installs/ruby/3.3.0/bin/ceedling:25:in `load'
        from /home/user/.asdf/installs/ruby/3.3.0/bin/ceedling:25:in `<main>'

**Comment by mvandervoord** [comment]
I'm not going to find the duplicates of this bug at the moment, but it IS a duplicate. The problem is that Ruby 3+ have changed some of their API, including the wording of this function. You can grab the latest pre-release gem (0.32.xxxx) from the releases tab in github. Download it and install it by using `gem install --local <filename>`. This will clear up the problem for you.
