### ISSUE TITLE
Test report file not created

### ISSUE THREAD

**Issue by kafkaaaa** [ThrowTheSwitch/Ceedling#889]
Hello. 🌱

I'm now using **ver. [0.32.0-d9cb5e3]**

Here is my `project.yml` about Test Report Plugin : `report_tests_log_factory`
```
:plugins:
  :load_paths: []
  :enabled:
    #- beep                           # beeps when finished, so you don't waste time waiting for ceedling
    - module_generator               # handy for quickly creating source, header, and test templates
    #- gcov                           # test coverage using gcov. Requires gcc, gcov, and a coverage analyzer like gcovr
    #- bullseye                       # test coverage using bullseye. Requires bullseye for your platform
    #- command_hooks                  # write custom actions to be called at different points during the build process
    #- compile_commands_json_db          # generate a compile_commands.json file
    # - dependencies                   # automatically fetch 3rd party libraries, etc.
    #- subprojects                    # managing builds and test for static libraries
    #- fake_function_framework        # use FFF instead of CMock

    # Report options (You'll want to choose one stdout option, but may choose multiple stored options if desired)
    #- test_suite_reporter
    #- report_tests_raw_output_log
    - report_tests_pretty_stdout
    #- report_tests_ide_stdout
    #- report_tests_gtestlike_stdout
    #- teamcity_tests_report
    #- warnings_report
    - report_tests_log_factory

  
  :report_tests_log_factory:
    :reports:
      - json
      - junit
      - cppunit
      - html
    
    # Each report is written to a default filename within <build root>/artifacts/<context>:
      # JSON: tests_report.json
      # JUnit XML: junit_tests_report.xml
      # CppUnit XML: cppunit_tests_report.xml
      # HTML: tests_report.html
    :json:
      :filename: report_json.json
    :junit:
      :filename: report_junit.xml
    :cppunit:
      :filename: report_cppunit.xml
    :html:
      :filename: report_html.html
```

and my test results is... (cmd)

```
-----------------------
2 Tests 0 Failures 0 Ignored 
OK


Plugins (2) > :post_test_fixture_execute
----------------------------------------
 + report_tests_pretty_stdout...
 + report_tests_log_factory...

Plugins (2) > :post_build
-------------------------
 + report_tests_pretty_stdout...

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  2
PASSED:  2
FAILED:  0
IGNORED: 0

 + report_tests_log_factory...
```

So, why is there no report files on `<build root>/artifacts/` ??

p.s. I would like to know about changed command of `$ ceedling verbosity[4] test:all` from the previous version (0.31).
whenever running the test, should I typing `obnoxious` ?

**Comment by mvandervoord** [comment]
Since you're running a test, the reports should be in `build/artifacts/test`. From the output you have pasted there, it appears it's noticed the plugin is enabled (I see the log factory in your `post_text_fixture` call). 

So if the files still aren't getting generated, it's most likely that it isn't seeing your specification of what to generate. Looking at your `project.yml` file pasted above, if the spacing was preserved properly when you copied it, I think I see the problem: the `:report_tests_log_factory` section is indented to be part of `:plugins`. But it's its own section. So un-indent it and it should work.

If this fixes your issue, `Woo!`. If you could still leave this open for a bit, I'd like to fix a couple details you've uncovered:

(1) I should add the `:report_tests_log_factory` to the sample yaml file
(2) You are correct... we accidentally removed out shorthand for log level. In an attempt to make it shorter and clearer, we made it clearer but not shorter! Any combination of short/long flags should work. I'll fix it so `-v=4` is an option

**Comment by kafkaaaa** [comment]
Dear @mvandervoord 

`Woo!` It was `indent` problem indeed. so the `factory` can generate test reports. I like it.

If newer version updated with (1), (2) like you said, I believe it will be more convenient. 😊

Thank you and I really appreciate your reply.
