### ISSUE TITLE
Allow creation of mocks from the terminal

### ISSUE THREAD

**Issue by cjoecker** [ThrowTheSwitch/Ceedling#894]
I would love to have the option to create `CMock` mocks from the terminal like `ceedling mock:create[filename]`

**Comment by swaldhoer** [comment]
I would also like to use this feature.
However, to be aligned with other commands I think `ceedling mock:[filename]` would be better as it is then consistent with other Ceedling commands (i.e., `ceedling test:[filename]`, `ceedling gcov:[filename]`).
To be even more consistent `ceedling mock` should then expand `ceedling mock:all`.

**Comment by mkarlesky** [comment]
@cjoecker and @swaldhoer Can you explain what this feature achieves for you? What is your need to generate mocks independently of a build? Is the actual mock what you need or would specific details about what goes into a mock / how it's generated?

**Comment by swaldhoer** [comment]
The base line is, we are using ceedling directly to run our unit tests, i.e., we run `ceedling test:test_abc`.

However, the actual test implementations need to be passed to the static program analysis (SPA) build for MISRA-C, CWA, and architecture verification and some other analysis.
Oversimplified, the SPA build is basically the same as the ceedling build, except that the compiler is not `gcc` but the SPA compiler.
This SPA build needs to compile and link, therefore we need the generated mocks to run the build step.
Currently one needs to run a full ceedling build, just to pass things to the SPA compiler.

Therefore running
1. `ceedling mock:test_abc`
2. SPA build commands

instead of

1. `ceedling test:test_abc`
2. SPA build

would save lots of time and would feel somewhat more logical in this steps context.

**Comment by cjoecker** [comment]
@mkarlesky we have some large files where we want to mock just some functions, not all. It would be useful to generate a mock file from the terminal to copy/paste the functions I want to mock somewhere else.

**Comment by mkarlesky** [comment]
Ah ha. This is very helpful. Thank you.

With what we have planned for the future, generating individual mocks will not be terrifically hard. At the moment, it's not especially easy to crank out in light of other priorities. However, there is already plumbing that exists for a build-only test suite option that does everything except execute tests. This could be extended fairly easily to add a generation-only option as well where only file generation — mocks and runners (and preprocessed versions of files used as input for these) — happens.

I'll add this to the backlog. It will probably end up as a new feature added to the next minor point release following the massive release coming very, very soon.

I'm going to close this issue for now but know that it's in the backlog.
