### ISSUE TITLE
Unexpected return data of mock function after initialization in setUp function

### ISSUE THREAD

**Issue by mkj1998** [ThrowTheSwitch/Ceedling#896]
The Mock function ABC() initializes the **setUp** function, ABC IgnoreAndReturn (0), 
and then in the **test case**, I modified the return value ： ABC IgnoreAndReturn (1) 
Then when I first called the ABC function, I still received a return value of 0. 
when I continued to call the ABC function return 1 normally.

Maybe I don't know how to use it. If that's the case, I'm sorry
Thanks

**Comment by mvandervoord** [comment]
Return values are queued in the order you've specified. Therefore, by the time your test runs, you've told CMock that you don't care how many times the function is called. The first time it is called, it should return 0. The second time it is called, it should return 1. Because you've used IgnoreAndReturn, it doesn't care if it's more or less times than specified... any extra times it will continue to send whatever you specified last.

**Comment by mkj1998** [comment]
thanks, this is a silly question, sorry for taking up your time......

**Comment by mvandervoord** [comment]
No worries!

"Silly" questions (I didn't actually find it to be silly) point out where we could improve our documentation and education. Getting into testing isn't simple. Keep it up!
