### ISSUE TITLE
Tool definitions are not documented for `test_nested_includes_preprocessor` and `test_shallow_includes_preprocessor`

### ISSUE THREAD

**Issue by Julian-Wollersberger** [ThrowTheSwitch/Ceedling#909]
In the section [Ceedling’s default build step tool definitions](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/CeedlingPacket.md#ceedlings-default-build-step-tool-definitions), there is no documentation for the arguments to `test_shallow_includes_preprocessor` and `test_nested_includes_preprocessor`. 

These two tools seem to be new in 1.0.0. I use IAR instead of GCC, so the default config exits with a validation error that it can't find gcc. I think I got my own `test_file_preprocessor` tool working, which is also new, but documented.

I'm struggling with the `test_shallow_includes_preprocessor` though, since I don't really know what it is supposed to do. I found the defaults in `lib/defaults.rb`, which is helpful. But obviously, official documentation would be better.

**Comment by mkarlesky** [comment]
@Julian-Wollersberger This is a tricky one. These probably should be documented, but, they're not actually usable in the real world apart from GNU tools.

Ceedling relies on pretty simple inputs and outputs for build tools and plugin tools. Even compilation is simply a collection of paths, a handful of flags, and an input file; the compiler does the hard parts. Preprocessing is another animal entirely. Ceedling's preprocessing abilities are currently very tightly bound to `gcc` and `cpp`'s options and output. It's 99% likely that nothing else is a drop-in replacement. It's been forever since I worked with IAR, but, the last time I did it had no usable preprocessing output stage to get the results that Ceedling needs. As it is, even `gcc` and `cpp` do not provide everything Ceedling needs. We need to document this better to ensure that users do not go down the path of thinking they can incorporate another toolchain's preprocessing abilities.

Eventually, we hope to get to a plugin structure where you could just call out to a different tool with an expectation of the results it provides for preprocessing, but that's a ways off.

So, how do you handle this for your particular project? You have a couple options:

1. Use IAR for compilation and linking (and emulation if you're running test executables that way). Rely on the default `gcc` and `cpp` for Ceedling’s preprocessing. With some luck, header file macros to work around IAR language extensions, and such you might be able to get away with this GNU tools doing your preprocessing for you. The preprocessing steps Ceedling executes are only part of generating files your compiler then processes.
1. Use a [different release / test build technique](https://www.throwtheswitch.org/build/native) where your release build is all one toolchain and your test build is all with the GNU toolchain. This is typically our preferred approach as it gives greater flexibility and tends to promote better code overall. It does require some work to handle proprietary language extensions and things like register definitions.

**Comment by Julian-Wollersberger** [comment]
Thanks for the detailed answer. IMO it would be enough to add a note in docs about this limitation, that only GCC is officially supported for those tools.

To my situation:

IAR does have options to mimic what GCC does here, specifically `--preprocess` and `--dependencies`, but I don't know if that is enough for ceedling's use case. And since my team's ceedling config is an organically grown pile of hacks, I'd like to avoid making it more unstable with maybe-compatible tool definitions. (That's why I'm excited about mixins. They'd solve several of those hacks)

So your suggestion 1 sounds good. I'll try that. The only downside is that everyone in my team will need to manually install MinGW. Our code base already compiles with GCC, so that's not a problem.

Regarding 2, that's a refactoring I have actually planned for a while. It's complicated for compliance reasons. The main benefit would actually be performance. Compiling and running the tests on x86_64 would be about four times faster than compiling for ARM and running them in a simulator. 

As a general note, the docs have noticeably improved overall, so thanks for that ^^

**Comment by mkarlesky** [comment]
@Julian-Wollersberger Do kick the tires on option (1) and let us know how it goes. I could be forgetting something, but I _think_ Ceedling’s new and improved preprocessing should be up to this task. The trick will be in dealing with IAR-specific details in header files that get run through Ceedling's preprocessing. Success will be a matter of how you write macros, “wrap” header files, and conditionally include files and whatnot. You might just find some lurking bugs by mixing toolchains. That's what I'm interested to learn about here. I'll close the issue for now but feel free to reopen it as you find things.

We're excited about Mixins as well. They replaced as many as a half-dozen documented and undocumented features.

Glad to hear you are finding the documentation improved. That's been a big priority for this upcoming 1.0.0 release. Easily a third of the total effort has been in documentation. We still have a ways to go at that.
