### ISSUE TITLE
Linker flag as 'suffix'

### ISSUE THREAD

**Issue by 0ge** [ThrowTheSwitch/Ceedling#92]
I'm linking in math.h from my source. This compiles fine on my machine (Mac) but when uploaded to our build server (Ubuntu), it fails since -lm is not specified for the linker. This is a bit problematic since this flag must be added _last_ to the linker command; for example (totally guessing here)

```
gcc "file.o" -o "file.out" -lm
```

However, setting the flag in the project.yml will not work, since this will add the flag after `gcc`, not at the end. I've worked around this by editing the ceedling/lib/ceedling/defaults.rb as follows, but its a bit hacky and I bet that next time I update Ceedling this will be lost and I'll be back wondering what I have changed. Any suggestions? (Other than saving a patch for future reference)

```
diff --git a/vendor/ceedling/lib/ceedling/defaults.rb b/vendor/ceedling/lib/ceedling/defaults.rb
--- a/vendor/ceedling/lib/ceedling/defaults.rb
+++ b/vendor/ceedling/lib/ceedling/defaults.rb
@@ -32,6 +32,7 @@
   :arguments => [
     "\"${1}\"".freeze,
     "-o \"${2}\"".freeze,
+    "-lm".freeze,
     ].freeze
   }
```

**Comment by leoedin** [comment]
This is an issue I've come across as well. I agree that the update you proposed is not very nice, and not really a viable long term solution.

[It seems that this issue is fixed in GCC 5.4 and later](http://stackoverflow.com/a/12165016/685157). Unfortunately the default on Ubuntu still appears to be 4.9. Relying on the compiler is also not a very nice solution.

Is there any way Ceedling can define the position of linker flags as a configuration parameter?

**Comment by 0ge** [comment]
Better yet to have a completely separat variable for linker flags so that flags that need to be directly after `gcc` can still be there, and for the rare case of `-lm` and such, can be placed at the end, I think.

**Comment by 0ge** [comment]
Here is another case: #136

**Comment by Letme** [comment]
Since #136 was resolved - I think we can close this as well.

**Comment by mvandervoord** [comment]
Thanks. I think so too.
