### ISSUE TITLE
GCov fail when testing c file without a header

### ISSUE THREAD

**Issue by rickymohk** [ThrowTheSwitch/Ceedling#926]
I want to test a file that doesn't have a corresponding header file. e.g.
src/foo.c
```c
int sum(int a, int b)
{
    return a + b;
}
```

test/test_foo.c
```c
#include "unity.h"
#include "foo.c"

void test_sum(void)
{
    TEST_ASSERT_EQUAL(3, sum(1, 2));
}
```

`ceedling test:test_foo` runs without issue
```
Test 'test_foo.c'
-----------------
Running test_foo.out...

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  1
PASSED:  1
FAILED:  0
IGNORED: 0
```

But `ceedling gcov:test_foo` fails with the following error
```
Test 'test_foo.c'
-----------------
Running test_foo.out...

--------------------------
GCOV: OVERALL TEST SUMMARY
--------------------------
TESTED:  1
PASSED:  1
FAILED:  0
IGNORED: 0


---------------------------
GCOV: CODE COVERAGE SUMMARY
---------------------------
build/gcov/out/foo.gcno:cannot open notes file
build/gcov/out/foo.gcda:cannot open data file, assuming not executed
ERROR: Shell command failed.
> Shell executed command:
'gcov -n -p -b -o "build/gcov/out" "foo.c"'
> Produced output:
No executable lines
> And exited with status: [1].

Exception raised in plugin: gcov, in method post_build
/home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/tool_executor.rb:88:in `exec': ShellExecutionException (ShellExecutionException)
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/plugins/gcov/lib/gcov.rb:89:in `block in report_per_file_coverage_results'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/plugins/gcov/lib/gcov.rb:86:in `each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/plugins/gcov/lib/gcov.rb:86:in `report_per_file_coverage_results'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/plugins/gcov/lib/gcov.rb:63:in `post_build'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/plugin_manager.rb:99:in `block in execute_plugins'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/plugin_manager.rb:97:in `each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/plugin_manager.rb:97:in `execute_plugins'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/plugin_manager.rb:85:in `post_build'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/rakefile.rb:78:in `block in <top (required)>'
```

**Comment by mkarlesky** [comment]
Hi, @rickymohk. So sorry about this. Thank you for submitting the issue. I can confirm that the various improvements in the 1.0.0 prerelease have already fixed this problem some time ago. We don't have the resources to support multiple active versions of Ceedling. Since 1.0.0 is (finally) on the verge of being released, this bug in 0.31.1 will, unfortunately, need to go unfixed.

**Comment by rickymohk** [comment]
Is there any workaround for 0.31.1? I want  to at least create an empty coverage for that file so the denominator of the overall coverage is correct. But I can't because if I include this file it will crash and abort the process and any files come after will not be covered.

**Comment by Letme** [comment]
You seem to be having whole other problem than you underlined.

Why are you including `foo.c` in your test file and not `foo.h` and let compiler create foo.c and then reference its functions in test? Then your gcov will find the foo.c (which now it doesn't, because it is inlined - basically part of test file). If that foo.c is actually static inline implementation file, then name it at least foo.h and include that into the foo.c (just with that include) you will be able to see the coverage of that file.

**Comment by rickymohk** [comment]
As I mentioned because there is no foo.h. I am tasked to write tests for an existing project which source code can no longer be modified. Anyway I end up writing a bash script to run `ceedling gcov` on each test file one by one so that it doesn't stop when one fails. Thank you for helping me out.

**Comment by mkarlesky** [comment]
@rickymohk The simplest option I can think of for a workaround is:

1. Expand your `:paths` ↳ `:test` list in your project configuration to add some appropriately named support directory. This directory would not be part of the source structure you aren't able to modify.
1. Drop in an empty _foo.h_ (with some comment inside explaining the issue) into that new support directory.
1. Modify your test to `#include "foo.h"` instead of _foo.c_.

That _should_ work. You'd be basically conforming to the normal Ceedling convention (that the Gcov plugin in 0.31.1 is too rigidly expecting) and simply inserting a search path and header file that only exist in your test build.

**Comment by rickymohk** [comment]
> @rickymohk The simplest option I can think of for a workaround is:
> 
> 1. Expand your `:paths` ↳ `:test` list in your project configuration to add some appropriately named support directory. This directory would not be part of the source structure you aren't able to modify.
> 2. Drop in an empty _foo.h_ (with some comment inside explaining the issue) into that new support directory.
> 3. Modify your test to `#include "foo.h"` instead of _foo.c_.
> 
> That _should_ work. You'd be basically conforming to the normal Ceedling convention (that the Gcov plugin in 0.31.1 is too rigidly expecting) and simply inserting a search path and header file that only exist in your test build.

Thank you. This way I can test those files properly.
