### ISSUE TITLE
gcov does not generate html reports correctly.

### ISSUE THREAD

**Issue by EdgyHedgehog** [ThrowTheSwitch/Ceedling#958]
Hi,

I was trying to get Ceedling to generate gcov reports. It does run tests and generate all the html reports fine, for as long as the source under test is within the file tree of the Ceedling project. If the source code is being provided from the outside of the tree, the tests do run fine, even with gcov coverage report, but the html files do not get generated correctly in the build/artifacts/gcov location. I have tried this with Ceedling versions 0.31.x and 1.0.x - they both give exactly the same result. What is interesting, that despite incorrectly generated html files, the gcda and .gcno files do get generated in build/gcov/out location.

Does anyone know what might be the issue here?

In the project.yml file:
`:paths:`
  `:source:`
    `- src/**` - code from here is going to get a correct the html report
    `- ../src/**` - code from here is not going to get a correct html report

Kind regards.

**Comment by art-of-dom** [comment]
What output are you getting and what specific commands are you running? This will help understand exactly what's going wrong.

 The `utils:gcov` is specifically what generates the html report from ceedling. The html report is generated by an external command gcovr which you may need a specific version so if you can let us know what version you are using that would help.

P.S. coming back to this repo after a long break. Haven't fully test any 1.0.0 candidates yet so there may be additional things needed for html reports to work with 1.0.0

**Comment by EdgyHedgehog** [comment]
I have made this example repository (I hope it is publicly visible) which produces a problem on my machine:

https://github.com/EdgyHedgehog/ceedling_gcov_example

Commands are in the repo README file. I hope it helps.

**Comment by art-of-dom** [comment]
@EdgyHedgehog So the issue is how Ceedling utilizes gcovr. The version of gcovr I have which is 4.2 the command ` gcovr -r .. build/gcov/out/`  shows the line coverage of ../src/code.c while ` gcovr build/gcov/out/` does not.

This would mean more configuration would be needed to get this specific use case to work and pass the root of your directory as defined by gcov. It also may not be simple as the root offset may also require the files passed to the report be adjusted. There may be other gcovr options to make this easier it would take a bit of reading regarding it.

**Comment by mkarlesky** [comment]
Hi, @EdgyHedgehog. I agree with @art-of-dom. Strictly speaking, this is not a Ceedling issue but a matter of configuring the external tool GCovr for your report generation setup. It appears the problem is simply that the paths `gcovr` is aware of do not include the paths of your source files.

As I recall, `gcovr` defaults to only processing the source files that are in the directory tree immediately beneath its working directory at runtime. So, as @art-of-dom said, you'll need to help `gcovr` out with more configuration. See the Ceedling 1.0.0 Gcov Plugin README for some good details on all this.

In particular, I think you may want to set the `:report_root` option in your Ceedling `:gcov` plugin configuration ([docs](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/plugins/gcov/README.md#common-gcovr-options)) and optionally set some exclude filters as you may need to go with an overly expansive parent directory.

To figure this out, you may want to simply build your project with Ceedling and then run `gcovr` directly with options experiments until you get the results you want. Then, you can move those options into your Ceedling project file. Alternatively, `gcovr` will recognize its own configuration file in the working directory from which it's run (same as the working directory of Ceedling), and you can skip lots of `gcovr` settings in your Ceedling project.

I'm going to close this issue for sake of housekeeping as it's not technically a Ceedling bug or feature. But, if you need more help please comment in the closed issue. Or, if you come across a Ceedling bug or feature need, please reopen this issue.
