### ISSUE TITLE
Test executable `*.out` seems to have crashed

### ISSUE THREAD

**Issue by SamPeng87** [ThrowTheSwitch/Ceedling#964]
测试用例是都能通过的。用如下命令查看

ceedling -v=obnoxious

```
Running test_modbus_protocol.out...

> Shell executed command:
`build/test/out/test_modbus_protocol/test_modbus_protocol.out`
> And terminated with exit code: [0]

☠️ ERROR: Test executable `test_modbus_protocol.out` seems to have crashed

🪲 ERROR: Test executable `test_modbus_protocol.out` failed.
> Produced no output
> And terminated with exit code: [0] (failed test case count).
> Causes can include a bad memory access, stack overflow, heap error, or bad branch in source or test code.


> Shell executed command:
`build/test/out/test_modbus_protocol/test_modbus_protocol.out -n test_ResponseModbusWriteSingleRegister`
> Produced output: 
test_modbus_protocol.c:35:test_ResponseModbusWriteSingleRegister:PASS

```

I don't know why running test_modbus_protocol.because tests is can success execute

**Comment by mkarlesky** [comment]
Hi, @SamPeng87. So sorry for this trouble.

You are correct that the test executable is producing test results. _**But**_, the test results are not complete. Complete test results include a final tally of all tests run, how many passed, how many failed, etc. That is missing here.

What's curious is that the test executable exited with a successful [0] exit code.

Could you please try two things?
1. Run the test executable yourself in a terminal: `$ build/test/out/test_modbus_protocol/test_modbus_protocol.out`
1. Run it again with the `-n` flag as your build ran it: `$  build/test/out/test_modbus_protocol/test_modbus_protocol.out -n test_ResponseModbusWriteSingleRegister`

We're wondering if the filter flag for the test executable is somehow preventing the final test summary from being output. If so, this would suggest the issue is with the Unity framework.

If both of your tests at the terminal produce full results, then it would seem the shell Ceedling runs is somehow cutting off the final test summary from the test executable.

**Comment by SamPeng87** [comment]
I have found the problem. There is a property that needs to be assigned NULL even if it is empty because the code accesses this property. But strangely, Unity didn't inform me; logically, the code has even passed through this segment. My understanding is that if there is a problem, accessing an unexpected memory address will directly cause a crash. This error message is very vague; I only noticed it by chance when I saw an Error.

If Unity stops testing directly upon discovering a crash, it would be reasonable. Interestingly, if it is indeed a null pointer, Unity will crash correctly.
The sample code is as follows:

```
//define help struct 
ModbusSlaveRequest mockSlaveRequest;
mockSlaveRequest.slave = 0x01;
mockSlaveRequest.responseCallback = NULL;

// logic in us .c file
if (protocol->slave.responseCallback) {
      protocol->slave.responseCallback(&protocol->slave);
}
```

From the operation perspective, if there is no `mockSlaveRequest.responseCallback = NULL`, the phenomenon mentioned earlier will occur, and the test can pass, and this judgment will also run normally. If `mockSlaveRequest.responseCallback = NULL` is set, everything works fine.

**Comment by SamPeng87** [comment]
It's very strange, this bug disappeared because I split this test file into several parts. I spent a whole day making adjustments. I'll reproduce it later.

Yesterday I tested: build/test/out/test_modbus_protocol/test_modbus_protocol.out

Executing this alone will not work

**Comment by SamPeng87** [comment]
I reproduced it.

```
void test_ModbusRequestFrameResp_success_branch(void)
{
    // Arrange
    uint8_t mockData[8] = {0x01, 0x03, 0x00, 0x01, 0x00, 0x02,0x74, 0xFD}; // 读寄存器请求
    uint16_t mockCrc = 0xFD74;
    uint16_t mockSlave = 0x01;
    uint8_t mockFn = 0x03;
    uint16_t mockDataLen = 8;

    // Mock CRC16 calculation
    CRC16_ExpectAndReturn(mockData,6, mockCrc);


    ModbusSlaveRequest mockSlaveRequest;
    mockSlaveRequest.slave = mockSlave;
    mockSlaveRequest.readHoldingRegisters = readHoldingRegisters;
//    mockSlaveRequest.responseCallback = responseCallback;  <---
    mockSlaveRequest.writeSingleRegister = writeSingleRegister;
    mockSlaveRequest.writeMultipleRegisters = writeMultipleRegisters;
//    responseCallback_Ignore(); <---

    readHoldingRegisters_IgnoreAndReturn(1);

    struct ModbusRequestProtocol thisTestProtocol;
    thisTestProtocol.slave = mockSlaveRequest;

    // Act
    uint8_t result = ModbusRequestFrameResp(&thisTestProtocol, mockSlave, mockFn, mockDataLen, mockData);

    // Assert
    TEST_ASSERT_EQUAL_UINT8(1, result);
}
```
this is core testcase. you can see two comments. I deliberately caused another case to fail. For example

`test_ModbusRequestFrameResp_error_crc_return0`

if I uncomment two line code. run that command


`ceedling test:modbus_protocol` 

output:
```

👟 Executing
------------
Running test_modbus_protocol.out...
test_modbus_protocol.c:35:test_ResponseModbusWriteSingleRegister:PASS
test_modbus_protocol.c:56:test_ResponseModbusWriteMultipleRegisters:PASS
test_modbus_protocol.c:76:test_ResponseRequestReadModbusFrame:PASS
test_modbus_protocol.c:97:test_ModbusRequestFrameRouter_read_holding_register:PASS
test_modbus_protocol.c:112:test_ModbusRequestFrameRouter_write_single_register:PASS
test_modbus_protocol.c:127:test_ModbusRequestFrameRouter_write_multiple_register:PASS
test_modbus_protocol.c:144:test_ModbusRequestFrameRouter_unknown_function:PASS
test_modbus_protocol.c:154:test_ModbusRequestFrameResp_success_branch:PASS
test_modbus_protocol.c:188:test_ModbusRequestFrameResp_error_slave_id:PASS
test_modbus_protocol.c:223:test_ModbusRequestFrameResp_error_crc_return0:FAIL:Function responseCallback.  Called more times than expected.
test_modbus_protocol.c:258:test_ModbusRequestFrameResp_error_crc:FAIL:Function responseCallback.  Called more times than expected.
test_modbus_protocol.c:294:test_ModbusRequestFrameResp_error_data_len:PASS
test_modbus_protocol.c:329:test_ModbusByteReceiveRequest_read_holding_registers_success:PASS
test_modbus_protocol.c:364:test_ModbusByteReceiveRequest_write_single_register_success:PASS
test_modbus_protocol.c:395:test_ModbusByteReceiveRequest_write_multiple_registers_success:PASS
test_modbus_protocol.c:427:test_ModbusByteReceiveRequest_invalid_slave_id:PASS
test_modbus_protocol.c:447:test_ModbusByteReceiveRequest_unsupported_function_code:PASS
test_modbus_protocol.c:516:test_ModbusByteReceiveRequest_continuous_standard_frames:PASS
test_modbus_protocol.c:582:test_ModbusByteReceiveRequest_frames_with_noise:PASS
```

but, as you mentioned, step-by-step execution

` build/test/out/test_modbus_protocol/test_modbus_protocol.out -n test_ModbusRequestFrameResp_error_crc_return0`

output:
```
❯ build/test/out/test_modbus_protocol/test_modbus_protocol.out -n test_ModbusRequestFrameResp_error_crc_return0
test_modbus_protocol.c:223:test_ModbusRequestFrameResp_error_crc_return0:PASS

-----------------------
1 Tests 0 Failures 0 Ignored 
OK
```

This is the first place that seems off.

The second place. If I comment out the definitions in the code mentioned earlier, and then execute `ceedling test:modbus_protocol`


```
👟 Executing
------------
Running test_modbus_protocol.out...
☠️ ERROR: Test executable `test_modbus_protocol.out` seems to have crashed
test_modbus_protocol.c:35:test_ResponseModbusWriteSingleRegister:PASS
test_modbus_protocol.c:56:test_ResponseModbusWriteMultipleRegisters:PASS
test_modbus_protocol.c:76:test_ResponseRequestReadModbusFrame:PASS
test_modbus_protocol.c:97:test_ModbusRequestFrameRouter_read_holding_register:PASS
test_modbus_protocol.c:112:test_ModbusRequestFrameRouter_write_single_register:PASS
test_modbus_protocol.c:127:test_ModbusRequestFrameRouter_write_multiple_register:PASS
test_modbus_protocol.c:144:test_ModbusRequestFrameRouter_unknown_function:PASS
test_modbus_protocol.c:154:test_ModbusRequestFrameResp_success_branch:PASS
test_modbus_protocol.c:188:test_ModbusRequestFrameResp_error_slave_id:PASS
test_modbus_protocol.c:223:test_ModbusRequestFrameResp_error_crc_return0:PASS
test_modbus_protocol.c:258:test_ModbusRequestFrameResp_error_crc:PASS
test_modbus_protocol.c:294:test_ModbusRequestFrameResp_error_data_len:PASS
test_modbus_protocol.c:329:test_ModbusByteReceiveRequest_read_holding_registers_success:PASS
test_modbus_protocol.c:364:test_ModbusByteReceiveRequest_write_single_register_success:PASS
test_modbus_protocol.c:395:test_ModbusByteReceiveRequest_write_multiple_registers_success:PASS
test_modbus_protocol.c:427:test_ModbusByteReceiveRequest_invalid_slave_id:PASS
test_modbus_protocol.c:447:test_ModbusByteReceiveRequest_unsupported_function_code:PASS
test_modbus_protocol.c:516:test_ModbusByteReceiveRequest_continuous_standard_frames:PASS
test_modbus_protocol.c:582:test_ModbusByteReceiveRequest_frames_with_noise:PASS
```
You can see everything through the status.

I wonder if the default initial state for each case is PASS. If not executed, it defaults to PASS.

**Comment by mkarlesky** [comment]
@SamPeng87 I don't follow all the details you are reporting, but I think I understand enough to explain what is happening.

Unity is relatively simple. It's a collection of assertions and results reporting. It cannot directly detect a crash. It does not have hooks into the operating system in order to do such a thing. That'd be quite complicated to do in a cross-platform manner.

When C code encounters a bad reference—null pointer, wrong pointer, array access beyond allocated memory, etc., the behavior is undefined. There is no guarantee as to what will happen in C.

Ceedling is doing the crash detection by testing for a handful of telltale signs of a crash—exit status on some platforms, the presence of an OS-generated “Segmentation fault” string in the shell results, or a lack of full test reporting (because of early termination).

What you are seeing is Unity printing test results as the test executable runs test cases, and then it just ends when it executes the bad reference (sounds like an uninitialized value for a pointer—that's generally bad). Undefined behavior occurs causing the test executable to end prematurely before all test results are gathered and reported in a final summary. It happens to accidentally provide a successful exit code of 0.

So, Ceedling is correctly telling you that your test has crashed. Unfortunately, the results visible in logging misled you to think everything was okay or to cause you to think that Unity was not doing its job. I will update the crash detection reporting to make this much clearer in the future.

Incidentally, if you install `gdb` you can enable Ceedling's new feature that will tell you where the crash is happening when it detects one — `:project` ↳ `:use_backtrace: :gdb`. I'd be very interested to see what happens if you were to install GDB and enable this feature. I suspect Ceedling's backtrace reporting would lead you directly to the uninitialized pointer you already discovered as the problem.

I don't see a Unity or Ceedling bug here. Everything is working as intended. I do see an opportunity for clearer reporting, though. I will make that change to add to another prerelease version of 1.0.0 before we officially release it. I will close this issue for now. Feel free to continue commenting in it with any further findings. If you do encounter a true bug, please reopen this issue or file a new one.
