### ISSUE TITLE
module_generator maybe can't use source_root and inc_root in 1.0.0-13d0e3d

### ISSUE THREAD

**Issue by PengLingJun** [ThrowTheSwitch/Ceedling#965]
My configuration is as follows
```
:module_generator:
  :project_root: ./
  :source_root: src/
  :inc_root: Inc/
  :test_root: ../tests/test/
```

that configuration is in last release 0.31.that is work good。

if I use `ceedling module:create[../App/Conn/:common]`
that will created common.h in ../App/Conn/Inc and common.c in ../App/Conn/Src

now,I upgrade to 1.00-13d0e3d

that not work,ceedling not use source_root and inc_root.only will create .c/.h  all in ../App/Conn/.

maybe some thing is wrong?

**Comment by mvandervoord** [comment]
There are a few changes to the way module_generator works. By default, it will now use the first path in your src, test, and inc listing in the standard paths portion of the project.yml file. You can override these, just like before, but the name has changed:

```
:module_generator:
  :path_src:
  :path_inc:
  :path_tst:
```

When you specify a path during the create command, it now will intelligently use the paths that it knows about to find the best match. So you no longer need to specify a full path (unless you have a bunch of similar paths). For example, let's say my project uses the following paths:

Say your directory structure looks like this:

```
:paths:
  :source:
    - lab/src
    - lair/src
    - other/src
  :test:
    - lab/test
    - lair/test
    - other/test
```

In this case, the `lair:` hint would make the module generator guess you want your files here:

 - source files: `lair/src` (because it's a close match)
 - include files: `lair/src` (because no include paths were listed)
 - test files: `lair/test` (because it's a close match)

Instead, if your directory structure looks like this:

```
:paths:
  :source:
    - src/**   #this might contain subfolders lab, lair, and other
  :include:
    - inc/**   #again, this might contain subfolders lab, lair, other, and shared
  :test:
    - test
```

In this case, the `lair:` hint would make the module generator guess you want your files here:

 - source files: `src/lair` (because it's a close match)
 - include files: `inc/lair` (because it's a close match)
 - test files: `test` (because there wasn't a close match, and this was the first entry on our list)
