### ISSUE TITLE
Use real implementation of a mocked function

### ISSUE THREAD

**Issue by radoslav06** [ThrowTheSwitch/Ceedling#968]
Hi,
I faced the problem that from one side I want to mock standard library function, in this case it is `memset` ( the module under test is using it); on the other side I want to use the `memset` real implementation in my unit test code.  
I am trying to mock `memset` from embedded standard library for our ARM target and I want to use `memset` implementation for host PC (gcc) in my test code.  
Is it possible?

I am using:
```
Ceedling => 1.0.0-a1e6b24
       CMock => 2.5.4
       Unity => 2.6.0
       CException => 1.3.4
```

Thanks in advance!

**Comment by mvandervoord** [comment]
I see two possible (slightly different) interpretations in your question and I'm not sure which you're asking, so I'll answer both.

ANSWER 1:

If you're talking about building a single unit test module which uses both the real `memset` AND a mocked `memset` from within the first test, it's not possible. The linker can only link against one copy of `memset`, so there isn't a way to differentiate the two. 

There IS a common workaround, though. For the memset that your ARM target is using, if you're able to tweak the source code, people often create a thin header file wrapper for some of their standard libraries. For example, the header file might be called `system.h` and it might include something like this:

```
#ifdef TEST
void MEMSET(void* ptr, int x, size_t n);
#else
#include "stdlib.h"
#define MEMSET memset
#endif
```

Instead of including `stdlib.h` and using `memset` in most of your code, you can instead include `system.h` and use `MEMSET`. When compiling for release, it's going to work exactly the same as usual. It'll include stdlib automatically for you and use the standard library `memset`. During tests, it will instead use the function definition above, which is mockable... so you can include `mock_system.h` and then use `MEMSET_Expect` etc.

Often, this resolves the problem competely in that places that call `memset` during a test will still be calling the real one, and others are now calling the mockable `MEMSET`. If you're still in a situation where part of your code wants a "real" `MEMSET` and part wants a mock, you can use CMock's stubbing features to direct the calls to either test code or `memset`.

Make sense?

ANSWER 2:

It might be that you were just asking if some tests can mock `memset` while others use the real `memset`... In that case, this all gets simpler. You can divide those tests into different test files. In the test file which wants to use the real memset, include `stdlib.h`. In the other, include `mock_stdlib.h`. Each test file is compiled separately, so it's not a problem.

I hope one of these is helpful. If I'm off the mark or have missed a detail, just say the word!  :)

**Comment by radoslav06** [comment]
Thanks you for the detailed explanation, the ANSWER 1 is my scenario.  
I understand the solution, the only problem I have with it is that it requires quite a bit of overhead and source code modification. I was thinking that maybe the original function is available through some other symbol (like in `--wrap` in gcc), but I see that cmock does not work at the linker level.  
Probably, the preprocessor is the only solution then. I am just thinking if I can leave the code untouched and only replace the header files, just an idea:  

In application code:
```C
#ifdef TEST
#include "test_string.h"
#else
#include "string.h"
#endif
```
In the `test_string.h`:
```C
#ifndef TEST_USE_ORIGINALS
#define memset test_memset
#endif

void * test_memset(void *s, int c, size_t n);
```
And finally in the test file:
```C
...
#define TEST_USE_ORIGINALS
#include "mock_test_stdlib.h"
...
```

**Comment by mvandervoord** [comment]
Something like that will also work. In any case, it's work-arounds. :)
